import Link from "next/link";
import { JOB_ROLES } from "@/data/job-roles"; // Changed to JOB_ROLES
import { FileText, ChevronRight } from "lucide-react";

export const metadata = {
  title: "AI Cover Letter Examples & Samples | Fancy Digitals",
  description: "Explore 50+ professionally written cover letter examples for different industries. Generate your own with Fancy Digitals AI.",
};

export default function CoverLetterHub() {
  return (
    <div className="min-h-screen bg-gray-50 pt-20 pb-12">
      <div className="max-w-6xl mx-auto px-4">
        <div className="mb-12 text-center">
          <h1 className="text-4xl font-extrabold text-gray-900 mb-4">
            Industry-Specific <span className="text-[#ff914d]">Cover Letter</span> Samples
          </h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            High-converting cover letter examples generated by AI. Choose your role to get started.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {JOB_ROLES.map((role) => ( // Changed to JOB_ROLES
            <Link
              key={role.slug}
              href={`/cover-letter-for/${role.slug}`}
              className="group p-4 bg-white border border-gray-200 rounded-xl hover:border-[#ff914d] hover:shadow-md transition-all flex items-center justify-between"
            >
              <div className="flex items-center gap-3">
                <div className="p-2 bg-orange-50 rounded-lg group-hover:bg-[#ff914d] group-hover:text-white transition-colors text-[#ff914d]">
                  <FileText size={20} />
                </div>
                <span className="font-medium text-gray-800 group-hover:text-[#ff914d]">
                  {role.title} Cover Letter
                </span>
              </div>
              <ChevronRight size={18} className="text-gray-400 group-hover:text-[#ff914d]" />
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}