export const tools = [
  

  {
  slug: "ai-resume-builder",
  name: "AI Resume Builder",
  category: "AI Tools",
  desc: "Build ATS-optimized resumes in 30 seconds with AI. 6 premium templates, photo upload, job match scoring.",
  longDesc: "Generate professional, ATS-friendly resumes powered by AI. Choose from 6 premium templates, customize colors, add your photo, and download as PDF. Built-in ATS compatibility checker, job match analyzer, and AI auto-fix to optimize your resume for any job description.",
  status: "Live",
  image: "/tools/ai-resume.png",
  published: true,
  order: 0,
  isLive: true,
  isAI: true,
  requiresLogin: true,
  accent: "#075a01",
  accentLight: "from-[#075a01]/10 to-[#0a8f01]/10",
  popular: true,
  href: "/dashboard/tools/ai-resume-builder",
  keywords: [
    "ai resume builder",
    "free resume builder",
    "ats resume builder",
    "resume generator ai",
    "professional resume maker",
    "cv builder online",
  ],
  features: [
    "AI-powered content generation",
    "6 premium templates (Pro)",
    "ATS compatibility score",
    "Job match analyzer",
    "AI auto-fix optimization (Pro)",
    "Photo upload support",
    "Real PDF download",
    "Custom accent colors (Pro)",
    "Auto-save form data",
  ],
  whoFor: [
    "Job seekers",
    "Career changers",
    "Recent graduates",
    "Professionals updating their CV",
  ],
  faq: [
    { q: "Is the resume builder free?", a: "Yes — 3 free resumes per day with the Basic template. Pro unlocks unlimited resumes, 5 premium templates, and AI optimization." },
    { q: "Is my resume ATS-friendly?", a: "Yes. Every resume passes our ATS compatibility check and includes a score with improvement tips." },
    { q: "Can I download as PDF?", a: "Yes. Pro users get instant PDF download. Free users can print to PDF using the browser." },
  ],
},
{
  slug: "ai-cover-letter",
  name: "AI Cover Letter Generator",
  category: "AI Tools",
  desc: "Generate tailored cover letters in seconds. Auto-fills from your resume. Multiple tones and lengths.",
  longDesc: "Create personalized cover letters that match any job description. Choose your tone (professional, enthusiastic, direct, creative) and length. Auto-fills from your AI Resume Builder data for maximum efficiency.",
  status: "Live",
  image: "/tools/ai-cover-letter.png",
  published: true,
  order: 0,
  isLive: true,
  isAI: true,
  requiresLogin: true,
  accent: "#7c3aed",
  accentLight: "from-[#7c3aed]/10 to-[#ec4899]/10",
  popular: true,
  href: "/dashboard/tools/ai-cover-letter",
  keywords: [
    "ai cover letter generator",
    "free cover letter builder",
    "cover letter maker ai",
    "job application letter generator",
  ],
  features: [
    "AI-tailored to any job description",
    "4 tone options",
    "3 length options",
    "Auto-fills from your resume",
    "Personalized hiring manager greeting",
    "Free download",
  ],
  whoFor: [
    "Job applicants",
    "Career changers",
    "Recent graduates",
    "Anyone applying to multiple jobs",
  ],
  faq: [
    { q: "How many cover letters per day?", a: "Free users get 3 per day. Pro users get unlimited." },
    { q: "Does it tailor to specific jobs?", a: "Yes. Paste the job description and AI will optimize the letter with relevant keywords and tone." },
  ],
},

  {
    slug: "seo-meta-tag-generator",
    name: "SEO Meta Tag Generator",
    category: "SEO",
    isAI: false,           // mark non-AI tools
requiresLogin: false,  // they don't need login
href: "/tools/meta-tag-generator",
    desc: "Generate perfect SEO meta titles and descriptions with a live Google preview and real-time scoring.",
    longDesc: "The free SEO Meta Tag Generator helps website owners, bloggers, and marketers create optimised meta titles and descriptions that rank higher on Google. Get real-time character count validation, keyword density checking, live Google search preview for desktop and mobile, Twitter card preview, Facebook OG preview, and instant HTML output ready to paste into your website.",
    status: "Live",
    image: "/tools/seo-planner.png",
    published: true,
    order: 1,
    isLive: true,
    accent: "#075a01",
    accentLight: "from-[#075a01]/10 to-[#0a8f01]/10",
    popular: true,
    keywords: [
      "seo meta tag generator",
      "meta description generator",
      "meta title generator",
      "seo title generator free",
      "google meta tags generator",
      "meta tag creator online",
      "open graph generator",
      "twitter card generator",
      "seo tag generator free",
      "website meta tags",
    ],
    features: [
      "Live Google desktop and mobile search preview",
      "Real-time character count with colour validation",
      "17-point SEO scoring engine",
      "Keyword density and position checking",
      "Twitter/X card preview",
      "Facebook OG preview",
      "One-click HTML copy to clipboard",
      "Download tags as .txt file",
    ],
    whoFor: [
      "SEO specialists",
      "Content writers",
      "Business owners",
      "Bloggers and publishers",
    ],
    faq: [
      { q: "What is a meta tag?", a: "A meta tag is an HTML element that provides information about a webpage to search engines and social media platforms. The two most important are the title tag and meta description." },
      { q: "How long should a meta title be?", a: "Between 30 and 60 characters. Google truncates titles longer than 60 characters in search results." },
      { q: "How long should a meta description be?", a: "Between 70 and 160 characters. Longer descriptions get cut off in Google search results." },
      { q: "Does meta description affect rankings?", a: "Not directly, but it affects click-through rate which signals quality to Google and indirectly improves rankings." },
      { q: "Is this SEO meta tag generator free?", a: "Yes. The SEO Meta Tag Generator is 100% free with no sign-up required. Use it as many times as you need." },
    ],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    category: "Writing",
    isAI: false,           // mark non-AI tools
requiresLogin: false,  // they don't need login
href: "/tools/word-counter",
    desc: "Count words, characters, sentences and paragraphs instantly with readability scoring and keyword density analysis.",
    longDesc: "The free Word Counter tool gives writers, students, SEO specialists and content creators a complete text analysis suite. Get instant word count, character count, reading time, speaking time, Flesch readability score, keyword density analysis, passive voice detection, adverb detection, platform character limit checking, auto-save, text cleaner, case converter, text diff comparison, and auto summariser.",
    status: "Live",
    image: "/tools/word-counter.png",
    published: true,
    order: 2,
    isLive: true,
    accent: "#0ea5e9",
    accentLight: "from-[#0ea5e9]/10 to-[#06b6d4]/10",
    popular: true,
    keywords: [
      "word counter",
      "word counter online",
      "online word counter free",
      "character counter",
      "word count tool",
      "count words online",
      "text analyser",
      "reading time calculator",
      "word counter no signup",
      "free word counter",
      "word count checker",
      "sentence counter",
    ],
    features: [
      "Real-time word and character count",
      "Reading time and speaking time estimate",
      "Flesch readability score",
      "Keyword density analysis with top keywords",
      "Passive voice and adverb detection",
      "Platform character limit checker for 10 platforms",
      "Auto-save, text cleaner, and case converter",
      "Text diff comparison and auto summariser",
      "Find and replace",
      "Word goal tracker",
    ],
    whoFor: [
      "Writers and bloggers",
      "Students and academics",
      "SEO content creators",
      "Social media managers",
    ],
    faq: [
      { q: "How accurate is the word counter?", a: "The counter uses precise word boundary detection — splitting on spaces, punctuation, and line breaks. It is accurate to the word." },
      { q: "What is a good readability score?", a: "For web content, aim for a Flesch Reading Ease score of 60 or above. Blog posts should target 60–70." },
      { q: "What is keyword density?", a: "Keyword density is how often a keyword appears as a percentage of total words. The ideal range is 1–2.5%." },
      { q: "Is the word counter free?", a: "Yes. The word counter is 100% free with no sign-up required." },
      { q: "Does the tool save my text?", a: "Yes. Auto-save stores your text in your browser every 1.5 seconds. Your text is never sent to any server." },
    ],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    category: "Security",
    isAI: false,           // mark non-AI tools
requiresLogin: false,  // they don't need login
href: "/tools/password-generator",
    desc: "Generate strong, secure, random passwords instantly with full control over length and character types.",
    longDesc: "The free Password Generator creates cryptographically strong passwords using your browser's built-in secure random number generator. Choose password length from 4 to 128 characters, toggle uppercase, lowercase, numbers and symbols, generate passphrases, bulk generate up to 50 passwords, check password strength in real time with entropy calculation and crack time estimate, and copy instantly. No data is ever sent to a server.",
    status: "Live",
    image: "/tools/password-generator.png",
    published: true,
    order: 3,
    isLive: true,
    accent: "#8b5cf6",
    accentLight: "from-[#8b5cf6]/10 to-[#a78bfa]/10",
    popular: true,
    keywords: [
      "password generator",
      "strong password generator",
      "random password generator free",
      "secure password generator",
      "password creator online",
      "password maker free",
      "passphrase generator",
      "bulk password generator",
      "password generator no signup",
      "free password generator",
      "complex password generator",
    ],
    features: [
      "Cryptographically secure random generation",
      "Adjustable length from 4 to 128 characters",
      "Toggle uppercase, lowercase, numbers, symbols",
      "Passphrase generator mode",
      "Bulk generate up to 50 passwords",
      "Real-time password strength scoring",
      "Entropy calculation and crack time estimate",
      "Character legend and session history",
    ],
    whoFor: [
      "Everyone with online accounts",
      "IT administrators",
      "Developers and engineers",
      "Business owners",
    ],
    faq: [
      { q: "Is this password generator secure?", a: "Yes. Passwords are generated using window.crypto.getRandomValues() — the same cryptographic randomness used by browsers for SSL. No passwords are stored or transmitted." },
      { q: "How long should my password be?", a: "At minimum 12 characters. For critical accounts, use 16–24 characters with all character types enabled." },
      { q: "Are the generated passwords saved anywhere?", a: "No. Everything runs in your browser. Nothing is sent to any server. Session history clears when you close the tab." },
      { q: "Is the password generator free?", a: "Yes. 100% free with no sign-up required." },
    ],
  },
  {
    slug: "invoice-generator",
    name: "Invoice Generator",
    category: "Business",
    isAI: false,           // mark non-AI tools
requiresLogin: false,  // they don't need login
href: "/tools/invoice-generator",
    desc: "Create professional invoices instantly and download as PDF. Free, no sign-up required.",
    longDesc: "The free Invoice Generator lets you create professional invoices in seconds. Add your business details, logo, client information, unlimited line items, taxes and discounts. Download as PDF or print directly. Supports 10 currencies including Nigerian Naira (NGN). Auto-saves to your browser. Save and load multiple invoices. No account needed, no watermark, completely free.",
    status: "Live",
    image: "/tools/invoice.png",
    published: true,
    order: 4,
    isLive: true,
    accent: "#075a01",
    accentLight: "from-[#075a01]/10 to-[#0a8f01]/10",
    popular: true,
    keywords: [
      "invoice generator free",
      "free invoice generator",
      "invoice maker online",
      "invoice creator free",
      "online invoice generator no signup",
      "pdf invoice generator free",
      "freelance invoice generator",
      "invoice generator Nigeria",
      "free invoice maker",
      "invoice template free",
      "create invoice free",
      "simple invoice generator",
    ],
    features: [
      "Professional invoice layout with your logo and branding",
      "Add unlimited line items with quantity and rate",
      "Automatic subtotal, tax and discount calculation",
      "Download as PDF or print directly",
      "Save and load invoices in browser",
      "10 currencies including NGN, USD, GBP, EUR",
      "Payment terms and bank details field",
      "Custom accent colour",
    ],
    whoFor: [
      "Freelancers and contractors",
      "Small business owners",
      "Agencies and studios",
      "Consultants and service providers",
    ],
    faq: [
      { q: "Is this invoice generator completely free?", a: "Yes. 100% free with no account required. No watermark, no hidden fees. Create and download unlimited invoices." },
      { q: "Can I save my invoice?", a: "Yes. Invoices auto-save in your browser. You can save multiple invoices and load them anytime." },
      { q: "What currencies are supported?", a: "All major currencies including Nigerian Naira (NGN), US Dollar (USD), British Pound (GBP), Euro (EUR), Ghanaian Cedi (GHS), Kenyan Shilling (KES), and more." },
      { q: "How do I download the invoice as PDF?", a: "Click Download PDF. The invoice opens in a print-ready view where you can save as PDF using your browser's built-in PDF printer." },
      { q: "Can I add my logo to the invoice?", a: "Yes. Upload your business logo and it will appear at the top of the invoice." },
    ],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    category: "Utilities",
    isAI: false,           // mark non-AI tools
requiresLogin: false,  // they don't need login
href: "/tools/qr-code-generator",
    desc: "Generate QR codes for URLs, text, WiFi, email, phone, SMS and vCards instantly. Download as PNG or SVG.",
    longDesc: "The free QR Code Generator creates high-quality QR codes for any purpose. Generate QR codes for websites, WiFi passwords, contact cards, phone numbers, emails, SMS and plain text. Customise colours, add a center logo, adjust size and error correction level. Download as PNG or SVG, scan QR codes from images or camera, generate in bulk from CSV, and create print-ready layouts.",
    status: "Live",
    image: "/tools/qr-code.png",
    published: true,
    order: 5,
    isLive: true,
    accent: "#f97316",
    accentLight: "from-[#f97316]/10 to-[#fb923c]/10",
    popular: true,
    keywords: [
      "qr code generator",
      "free qr code generator",
      "qr code maker online",
      "qr code creator free",
      "wifi qr code generator",
      "url to qr code",
      "custom qr code generator",
      "qr code generator no signup",
      "qr code scanner online",
      "bulk qr code generator",
      "qr code with logo",
      "qr code download free",
    ],
    features: [
      "Generate QR codes for URLs, text, WiFi, email, phone, SMS and vCards",
      "Live preview updates as you type",
      "Custom foreground and background colours with presets",
      "Add center logo — upload or choose preset icon",
      "Adjustable size from 100px to 1000px",
      "Error correction levels L, M, Q and H",
      "Download as PNG or SVG",
      "Scan QR codes from image upload or camera",
      "Batch generate from CSV file",
      "Print layout generator",
      "Session history",
    ],
    whoFor: [
      "Business owners and marketers",
      "Restaurant and retail owners",
      "Event organisers",
      "Developers and agencies",
    ],
    faq: [
      { q: "What is a QR code?", a: "A QR code is a two-dimensional barcode that can be scanned by any smartphone camera to instantly open a URL, connect to WiFi, save a contact, or perform other actions." },
      { q: "Are these QR codes free to use?", a: "Yes. All QR codes generated here are completely free, have no expiry date, and do not require an account." },
      { q: "What is error correction level?", a: "Error correction allows QR codes to be read even if partially damaged. Level H is best for printed materials that may get dirty or torn." },
      { q: "Can I use these QR codes commercially?", a: "Yes. There are no restrictions on commercial use. Use them on business cards, menus, packaging or any material." },
    ],
  },
  {
    slug: "color-palette-generator",
    name: "Color Palette Generator",
    category: "Design",
    isAI: false,           // mark non-AI tools
requiresLogin: false,  // they don't need login
href: "/tools/color-palette-generator",
    desc: "Generate beautiful color palettes from any base color, image, or preset style. Export as CSS, Tailwind, HEX, RGB and more.",
    longDesc: "The free Color Palette Generator creates professional color palettes for designers, developers, and brand builders. Generate harmonious color schemes using 7 color harmony rules — complementary, analogous, triadic, split-complementary, tetradic, monochromatic and shades. Extract palettes from uploaded images, explore 20 curated presets, check WCAG accessibility contrast ratios, and export in HEX, RGB, HSL, CSS variables, Tailwind config and SCSS format.",
    status: "Live",
    image: "/tools/color-palette.png",
    published: true,
    order: 6,
    isLive: true,
    accent: "#ec4899",
    accentLight: "from-[#ec4899]/10 to-[#f43f5e]/10",
    popular: true,
    keywords: [
      "color palette generator",
      "colour palette generator free",
      "color scheme generator",
      "color picker tool online",
      "brand color generator",
      "color palette from image",
      "complementary color generator",
      "color palette generator free",
      "css color palette",
      "tailwind color generator",
      "WCAG contrast checker",
      "color harmony generator",
    ],
    features: [
      "Generate palettes from any base color",
      "7 color harmony rules — complementary, analogous, triadic and more",
      "Extract palette from uploaded image",
      "20 curated preset palettes",
      "WCAG accessibility contrast checker",
      "Export as HEX, RGB, HSL, CSS variables, Tailwind config, SCSS",
      "One-click copy for every color and format",
      "Save and name custom palettes",
    ],
    whoFor: [
      "UI/UX designers",
      "Brand designers",
      "Web developers",
      "Marketing teams",
    ],
    faq: [
      { q: "What is a color palette?", a: "A color palette is a curated set of colors used together in a design to create visual harmony and guide attention." },
      { q: "What is color harmony?", a: "Color harmony refers to how colors work together visually. Complementary colors create contrast. Analogous colors create unity. Triadic uses three evenly spaced colors for vibrancy." },
      { q: "What is WCAG contrast ratio?", a: "WCAG defines minimum contrast ratios between text and background colors to ensure readability. A ratio of 4.5:1 is required for normal text." },
      { q: "Is the color palette generator free?", a: "Yes. 100% free with no sign-up required. Generate, save and export unlimited palettes." },
    ],
  },
  {
    slug: "hashtag-generator",
    name: "Hashtag Generator",
    category: "Social Media",
    isAI: false,           // mark non-AI tools
requiresLogin: false,  // they don't need login
href: "/tools/hashtag-generator",
    desc: "Generate the best hashtags for Instagram, TikTok, Twitter, LinkedIn, YouTube and Facebook instantly.",
    longDesc: "The free Hashtag Generator creates targeted hashtag sets for every major social media platform. Enter your topic, niche or keyword and get hundreds of relevant hashtags grouped by size — small, medium and large — for maximum reach. Build captions with hashtags included, save your favourite sets, copy everything with one click, and get platform-specific strategy for each network.",
    status: "Live",
    image: "/tools/hashtag-generator.png",
    published: true,
    order: 7,
    isLive: true,
    accent: "#e1306c",
    accentLight: "from-[#e1306c]/10 to-[#f77737]/10",
    popular: true,
    keywords: [
      "hashtag generator",
      "instagram hashtag generator free",
      "tiktok hashtag generator",
      "hashtag generator free",
      "best hashtags generator",
      "hashtag finder online",
      "hashtag creator free",
      "hashtag generator no signup",
      "free hashtag generator",
      "linkedin hashtag generator",
      "youtube hashtag generator",
      "social media hashtags generator",
    ],
    features: [
      "Generate hashtags for 6 platforms — Instagram, TikTok, Twitter, LinkedIn, YouTube, Facebook",
      "Hashtags grouped by size — small, medium and large",
      "Platform-specific limits and strategy advice",
      "25 niche categories",
      "Caption builder with hashtags included",
      "One-click copy for all hashtags",
      "Save favourite hashtag sets",
      "Hashtag count and platform limit tracker",
    ],
    whoFor: [
      "Content creators and influencers",
      "Social media managers",
      "Small business owners",
      "Digital marketing agencies",
    ],
    faq: [
      { q: "How many hashtags should I use on Instagram?", a: "Use 10–15 hashtags per post — a mix of small, medium and large for maximum reach. Instagram allows up to 30." },
      { q: "How many hashtags should I use on TikTok?", a: "Use 3–5 hashtags. Focus on 2–3 niche hashtags and 1–2 trending ones." },
      { q: "Is the hashtag generator free?", a: "Yes. 100% free with no sign-up required. Generate unlimited hashtag sets." },
      { q: "Can I save my hashtag sets?", a: "Yes. Click Save Set on any generated group and it will be stored in your browser for future use." },
    ],
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    category: "Utilities",
    isAI: false,           // mark non-AI tools
requiresLogin: false,  // they don't need login
href: "/tools/unit-converter",
    desc: "Convert length, weight, temperature, area, volume, speed, time, data, pressure and energy instantly.",
    longDesc: "The free Unit Converter handles every common conversion in one place across 10 categories. Convert between metric and imperial units for length, weight, temperature, area, volume, speed, time, digital storage, pressure and energy. Get instant real-time results as you type, a full conversion table for all units, formula display, saved favourite conversions, and conversion history.",
    status: "Live",
    image: "/tools/unit-converter.png",
    published: true,
    order: 8,
    isLive: true,
    accent: "#0ea5e9",
    accentLight: "from-[#0ea5e9]/10 to-[#06b6d4]/10",
    popular: true,
    keywords: [
      "unit converter",
      "unit converter online free",
      "length converter",
      "weight converter",
      "temperature converter",
      "metric to imperial converter",
      "online unit converter",
      "unit conversion calculator",
      "km to miles converter",
      "kg to lbs converter",
      "celsius to fahrenheit converter",
      "free unit converter",
    ],
    features: [
      "10 categories — length, weight, temperature, area, volume, speed, time, data, pressure, energy",
      "Metric and imperial unit support",
      "Instant real-time conversion as you type",
      "Full conversion table for every unit category",
      "One-click copy for every result",
      "Saved favourite conversions",
      "Conversion history",
      "Formula display for transparency",
    ],
    whoFor: [
      "Students and academics",
      "Engineers and scientists",
      "Chefs and home cooks",
      "Travellers and expats",
    ],
    faq: [
      { q: "How accurate are the conversions?", a: "All conversions use precise mathematical constants accurate to 10 decimal places." },
      { q: "Does this converter work offline?", a: "Yes. Once loaded, all conversions happen instantly in your browser with no internet required." },
      { q: "What temperature scales are supported?", a: "Celsius, Fahrenheit, Kelvin and Rankine are all supported with instant bidirectional conversion." },
      { q: "Is the unit converter free?", a: "Yes. 100% free with no sign-up required." },
    ],
  },
  {
  slug: "ai-landing-page-generator",
  name: "AI Landing Page Generator",
  category: "AI Tools",
  desc: "Describe your business — AI writes your full landing page, publishes it live, and captures leads. Free to try.",
  longDesc: "Generate a complete, conversion-optimized landing page in 60 seconds. AI writes your hero, features, benefits, pricing tables, FAQ, testimonials, team section, email capture, and CTAs — all in your tone and language. Publish live at your own URL instantly. Leads are captured and saved to your dashboard automatically. Supports 5 languages, 6 visual tones (Professional, Bold, Minimal, Playful, Friendly, Luxury), custom brand colors, logo upload, Tawk.to live chat, and Arabic RTL layout.",
  status: "Live",
  image: "/tools/ai-landing.png",
  published: true,
  order: 0,
  isLive: true,
  isAI: true,
  requiresLogin: true,
  accent: "#075a01",
  accentLight: "from-[#075a01]/10 to-[#0a8f01]/10",
  popular: true,
  href: "/dashboard/tools/ai-landing-page-generator",
  keywords: [
    "ai landing page generator",
    "free ai landing page generator",
    "landing page builder ai",
    "free landing page generator",
    "ai page builder free",
    "landing page creator ai",
    "generate landing page with ai",
    "ai website generator free",
    "free landing page builder no code",
    "best ai landing page generator",
    "publish landing page free",
    "ai powered landing page",
    "landing page generator no code",
    "create landing page ai",
    "ai marketing page builder",
    "landing page maker free online",
    "ai landing page with lead capture",
    "multilingual landing page generator",
  ],
  features: [
    "Full page written by AI in 60 seconds",
    "Publish live at your own URL (Pro)",
    "6 visual tones — Professional, Bold, Minimal, Playful, Friendly, Luxury",
    "5 languages — English, Spanish, French, Arabic, German",
    "Built-in email lead capture + lead dashboard",
    "Custom pricing tables (1–5 tiers)",
    "FAQ, testimonials, team section",
    "Custom brand colors + logo upload (Pro)",
    "Tawk.to live chat integration",
    "Arabic RTL layout support",
    "Video embed — YouTube & Vimeo",
    "Lead magnet with download link",
    "CSV lead export",
    "SEO meta included",
  ],
  whoFor: [
    "Startup founders validating ideas",
    "Marketers running campaigns",
    "Agencies building pages for clients",
    "Freelancers getting more clients",
    "Small businesses replacing expensive web designers",
  ],
  faq: [
    { q: "Is the landing page generator free?", a: "Yes — 2 generations per day on free plan. Pro unlocks unlimited generations, publishing, brand colors, multilingual pages, and more." },
    { q: "Can I publish my landing page live?", a: "Yes — Pro users publish instantly at fancydigitals.com.ng/p/your-slug. Fully hosted, no setup needed." },
    { q: "What languages does it support?", a: "English is free. Spanish, French, Arabic, and German are available on Pro. Arabic pages render right-to-left automatically." },
    { q: "How does lead capture work?", a: "Enable the Email Capture section when generating. All leads are saved to your Lead Dashboard automatically. Export to CSV anytime." },
    { q: "Does it work for any industry?", a: "Yes. The AI adapts copy, tone, and structure based on your product, audience, and goal." },
  ],
},

{
  slug: "ai-readiness-checker",
  name: "AI Readiness Checker",
  category: "AI Tools",
  desc: "See how AI assistants like ChatGPT, Gemini, Claude and Perplexity understand your website — with a prioritized improvement plan.",
  longDesc: "The free AI Readiness Checker analyzes your website across 10 signals AI assistants use to understand and recommend businesses — schema markup, structured data, meta tags, content quality, page speed, mobile experience, Knowledge Graph presence, entity clarity, AI readability, and trust signals. Get an overall AI Readiness Score (0-100), a full signal breakdown, a prioritized improvement plan, and side-by-side competitor comparison. Built for the new era of AI search — ChatGPT, Gemini, Claude, Perplexity, Copilot, and beyond.",
  status: "Live",
  image: "/tools/ai-readiness.png",
  published: true,
  order: 0,
  isLive: true,
  isAI: true,
  requiresLogin: false,
  accent: "#075a01",
  accentLight: "from-[#075a01]/10 to-[#0a8f01]/10",
  popular: true,
  href: "/free-ai-visibility-checker",
  keywords: [
    "ai readiness checker",
    "ai visibility checker",
    "ai seo tool",
    "chatgpt seo checker",
    "gemini visibility tool",
    "perplexity seo",
    "ai search optimization",
    "geo checker",
    "generative engine optimization",
    "ai website analyzer",
    "free ai seo audit",
    "schema checker",
    "structured data checker",
    "knowledge graph checker",
    "ai recommendation checker",
    "ai search visibility",
    "how to rank in chatgpt",
    "ai search ranking",
    "ai friendly website checker",
    "ai readiness score",
  ],
  features: [
    "AI Readiness Score (0-100) across 10 signals",
    "Technical SEO + schema + structured data analysis",
    "Knowledge Graph presence detection",
    "Entity clarity scoring",
    "AI readability assessment",
    "Prioritized improvement plan (Critical / High / Medium / Low)",
    "Detected signals breakdown",
    "Side-by-side competitor comparison (Pro)",
    "Scan history with score trend chart (Pro)",
    "Re-scan and track progress over time",
  ],
  whoFor: [
    "Business owners optimizing for AI search",
    "SEO professionals adapting to GEO",
    "Agencies auditing client sites",
    "Founders launching new products",
    "Marketers preparing for the AI search era",
  ],
  faq: [
    { q: "What is AI Readiness?", a: "AI Readiness measures how well your website is technically prepared to be understood, parsed, and cited by AI assistants like ChatGPT, Gemini, Claude, and Perplexity. It covers schema, content, meta tags, technical SEO, and structured data." },
    { q: "How is AI Readiness different from SEO?", a: "Traditional SEO targets Google's blue-link rankings. AI Readiness (sometimes called GEO — Generative Engine Optimization) targets being cited and recommended by AI models that synthesize answers instead of listing links." },
    { q: "Is it really free?", a: "Yes. 1 free scan per day with no signup. Sign up free for 3 scans per day. Pro unlocks unlimited scans, full reports, scan history, and competitor comparison." },
    { q: "Does a high score guarantee AI recommendation?", a: "No. AI Readiness measures on-page technical preparedness. Real recommendation also depends on real-world authority — backlinks, brand mentions, traffic, and Knowledge Graph presence. High Readiness + real authority = recommended by AI." },
    { q: "How long does a scan take?", a: "Usually 20–45 seconds. We run Google PageSpeed analysis, parse all your structured data, check Knowledge Graph, and calculate scores across 10 signals." },
  ],
},
  {
    slug: "brand-identity-builder",
    name: "Brand Identity Builder",
    category: "Design",
    desc: "Create a consistent brand system with colors, typography, and visual direction.",
    longDesc: "Define your brand colours, typography pairings, and visual direction in one place. Get consistency rules and guidance to apply across all your brand touchpoints.",
    status: "In Development",
    image: "/tools/brand-identity.png",
    published: true,
    order: 10,
    isLive: false,
    accent: "#8b5cf6",
    accentLight: "from-[#8b5cf6]/10 to-[#a78bfa]/10",
    popular: false,
    keywords: ["brand identity builder", "brand system generator", "brand color generator", "typography pairing tool"],
    features: [
      "Brand color system generation",
      "Typography pairing suggestions",
      "Visual identity direction",
      "Consistency rules and guidance",
    ],
    whoFor: ["New brands", "Rebrands", "Designers", "Client brand systems"],
    faq: [],
  },
  {
    slug: "email-sequence-mapper",
    name: "Email Sequence Mapper",
    category: "Email Marketing",
    desc: "Structure email flows that improve engagement, retention, and conversion.",
    longDesc: "Map out complete email sequences for onboarding, sales funnels, and lead nurturing. Get structured flow templates and copy blocks that move subscribers toward conversion.",
    status: "Coming Soon",
    image: "/tools/email.png",
    published: true,
    order: 11,
    isLive: false,
    accent: "#0ea5e9",
    accentLight: "from-[#0ea5e9]/10 to-[#06b6d4]/10",
    popular: false,
    keywords: ["email sequence mapper", "email funnel builder", "email marketing tool", "drip campaign planner"],
    features: ["Sequence structure builder", "Email copy blocks", "Lead nurturing flows", "Sales funnel mapping"],
    whoFor: ["Marketers", "Founders", "Email agencies", "E-commerce brands"],
    faq: [],
  },
  {
    slug: "conversion-audit-checklist",
    name: "Conversion Audit Checklist",
    category: "Optimization",
    desc: "Identify friction points and missed opportunities across your website.",
    longDesc: "Walk through a structured conversion audit of your website. Identify friction points, weak CTAs, trust signal gaps, and missed opportunities that are costing you customers.",
    status: "Coming Soon",
    image: "/tools/conversion.png",
    published: true,
    order: 12,
    isLive: false,
    accent: "#22c55e",
    accentLight: "from-[#22c55e]/10 to-[#4ade80]/10",
    popular: false,
    keywords: ["conversion audit", "website audit checklist", "CRO checklist", "conversion rate optimisation tool"],
    features: ["Page-by-page audit framework", "Friction point identification", "CTA and copy review", "Mobile experience checks"],
    whoFor: ["Website owners", "Conversion optimizers", "Agencies", "E-commerce stores"],
    faq: [],
  },
  {
    slug: "product-launch-planner",
    name: "Product Launch Planner",
    category: "Strategy",
    desc: "Plan launches with structure, clarity, and execution confidence.",
    longDesc: "Structure your entire product launch from pre-launch to post-launch. Get timeline frameworks, warm-up strategies, launch checklists, and post-launch review templates.",
    status: "Coming Soon",
    image: "/tools/launch.png",
    published: true,
    order: 13,
    isLive: false,
    accent: "#f97316",
    accentLight: "from-[#f97316]/10 to-[#fb923c]/10",
    popular: true,
    keywords: ["product launch planner", "launch checklist tool", "product launch strategy", "go to market planner"],
    features: ["Launch timeline builder", "Pre-launch checklist", "Audience warm-up strategy", "Post-launch review framework"],
    whoFor: ["Product founders", "SaaS teams", "Course creators", "Marketing leads"],
    faq: [],
  },
];