export const tools = [
  {
    slug: "seo-meta-tag-generator",
    name: "SEO Meta Tag Generator",
    category: "SEO",
    desc: "Generate perfect SEO meta titles and descriptions with a live Google preview and real-time scoring.",
    longDesc: "The SEO Meta Tag Generator helps website owners, bloggers, and marketers create optimised meta titles and descriptions that rank higher on Google. Get real-time character count validation, keyword density checking, live Google search preview, and instant HTML output ready to paste into your website.",
    status: "Live",
    image: "/tools/seo-planner.png",
    published: true,
    order: 1,
    isLive: true,
    accent: "#075a01",
    accentLight: "from-[#075a01]/10 to-[#0a8f01]/10",
    popular: true,
    keywords: ["seo meta tag generator", "meta description generator", "meta title generator", "seo title generator", "google meta tags", "meta tag creator"],
    features: [
      "Live Google desktop and mobile search preview",
      "Real-time character count with colour validation",
      "17-point SEO scoring engine",
      "Keyword density and position checking",
      "Twitter and Facebook OG preview",
      "One-click HTML copy to clipboard",
      "Download tags as .txt file",
    ],
    whoFor: [
      "SEO specialists",
      "Content writers",
      "Business owners",
      "Bloggers and publishers",
    ],
    faq: [
      { q: "What is a meta tag?", a: "A meta tag is an HTML element that provides information about a webpage to search engines and social media platforms. The two most important are the title tag and meta description." },
      { q: "How long should a meta title be?", a: "Between 30 and 60 characters. Google truncates titles longer than 60 characters in search results." },
      { q: "How long should a meta description be?", a: "Between 70 and 160 characters. Longer descriptions get cut off in Google search results." },
      { q: "Does meta description affect rankings?", a: "Not directly, but it affects click-through rate which signals quality to Google and indirectly improves rankings." },
    ],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    category: "Writing",
    desc: "Count words, characters, sentences and paragraphs instantly with readability scoring and keyword density analysis.",
    longDesc: "The Word Counter tool gives writers, students, SEO specialists and content creators a complete text analysis suite. Get instant word count, character count, reading time, speaking time, readability score, keyword density, passive voice detection, and platform character limit checks all in one place.",
    status: "Live",
    image: "/tools/word-counter.png",
    published: true,
    order: 2,
    isLive: true,
    accent: "#0ea5e9",
    accentLight: "from-[#0ea5e9]/10 to-[#06b6d4]/10",
    popular: true,
    keywords: ["word counter", "character counter", "word count tool", "online word counter", "count words online", "text analyser"],
    features: [
      "Real-time word and character count",
      "Reading time and speaking time estimate",
      "Flesch readability score",
      "Keyword density analysis",
      "Passive voice and adverb detection",
      "Platform character limit checker",
      "Auto-save, text cleaner, and case converter",
      "Text diff comparison and auto summariser",
    ],
    whoFor: [
      "Writers and bloggers",
      "Students and academics",
      "SEO content creators",
      "Social media managers",
    ],
    faq: [
      { q: "How accurate is the word counter?", a: "The counter uses the same word boundary detection as professional editors — splitting on spaces, punctuation, and line breaks. It is accurate to the word." },
      { q: "What is a good readability score?", a: "For web content, aim for a Flesch Reading Ease score of 60 or above. Blog posts and articles should target 60–70. Academic content naturally scores lower." },
      { q: "What is keyword density?", a: "Keyword density is how often a keyword appears as a percentage of total words. The ideal range is 1–2.5%. Over 3% risks being seen as keyword stuffing by Google." },
      { q: "Does the tool save my text?", a: "Yes. Auto-save is on by default and saves your text to your browser every 1.5 seconds. Your text is never sent to any server." },
    ],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    category: "Security",
    desc: "Generate strong, secure, random passwords instantly with full control over length and character types.",
    longDesc: "The Password Generator creates cryptographically strong passwords using your browser's built-in secure random number generator. Choose password length, include uppercase, lowercase, numbers and symbols, check password strength in real time, and copy instantly. No data is ever sent to a server.",
    status: "Live",
    image: "/tools/password-generator.png",
    published: true,
    order: 3,
    isLive: true,
    accent: "#8b5cf6",
    accentLight: "from-[#8b5cf6]/10 to-[#a78bfa]/10",
    popular: true,
    keywords: ["password generator", "strong password generator", "random password generator", "secure password generator", "password creator", "password maker"],
    features: [
      "Cryptographically secure random generation",
      "Adjustable length from 4 to 128 characters",
      "Toggle uppercase, lowercase, numbers, symbols",
      "Real-time password strength scoring",
      "Bulk generate up to 10 passwords at once",
      "One-click copy to clipboard",
      "Password history within session",
      "Entropy calculation",
    ],
    whoFor: [
      "Everyone with online accounts",
      "IT administrators",
      "Developers and engineers",
      "Business owners",
    ],
    faq: [
      { q: "Is this password generator secure?", a: "Yes. Passwords are generated using window.crypto.getRandomValues() which is the same cryptographic randomness used by browsers for SSL. No passwords are stored or transmitted." },
      { q: "How long should my password be?", a: "At minimum 12 characters. For critical accounts like banking and email, use 16–24 characters with all character types enabled." },
      { q: "Are the generated passwords saved anywhere?", a: "No. Everything runs in your browser. Nothing is sent to any server. The session history clears when you close the tab." },
      { q: "What makes a password strong?", a: "Length, randomness, and character variety. A 16-character password with uppercase, lowercase, numbers and symbols has over 85 bits of entropy — effectively uncrackable by brute force." },
    ],
  },
  {
    slug: "ai-landing-page-generator",
    name: "AI Landing Page Generator",
    category: "Marketing",
    desc: "Generate high-converting landing page structures and copy with clarity and speed.",
    longDesc: "Plan and structure high-converting landing pages using proven frameworks. Get section-by-section guidance, headline formulas, CTA logic, and value proposition structure without the guesswork.",
    status: "Coming Soon",
    image: "/tools/ai-landing.png",
    published: true,
    order: 4,
    isLive: false,
    accent: "#ff914d",
    accentLight: "from-[#ff914d]/10 to-[#ff6b1a]/10",
    popular: true,
    keywords: ["landing page generator", "ai landing page", "landing page builder", "conversion landing page"],
    features: [
      "AI-generated landing page structure",
      "Conversion-focused hero and CTA sections",
      "Clear value-proposition messaging",
      "Export-ready copy and layout outline",
    ],
    whoFor: [
      "Startup founders",
      "Product launches",
      "Marketing campaigns",
      "Client landing pages",
    ],
    faq: [],
  },
  {
    slug: "brand-identity-builder",
    name: "Brand Identity Builder",
    category: "Design",
    desc: "Create a consistent brand system with colors, typography, and visual direction.",
    longDesc: "Define your brand colours, typography pairings, and visual direction in one place. Get consistency rules and guidance to apply across all your brand touchpoints.",
    status: "In Development",
    image: "/tools/brand-identity.png",
    published: true,
    order: 5,
    isLive: false,
    accent: "#8b5cf6",
    accentLight: "from-[#8b5cf6]/10 to-[#a78bfa]/10",
    popular: false,
    keywords: ["brand identity builder", "brand system generator", "brand color generator", "typography tool"],
    features: [
      "Brand color system generation",
      "Typography pairing suggestions",
      "Visual identity direction",
      "Consistency rules and guidance",
    ],
    whoFor: [
      "New brands",
      "Rebrands",
      "Designers",
      "Client brand systems",
    ],
    faq: [],
  },
  {
    slug: "email-sequence-mapper",
    name: "Email Sequence Mapper",
    category: "Email Marketing",
    desc: "Structure email flows that improve engagement, retention, and conversion.",
    longDesc: "Map out complete email sequences for onboarding, sales funnels, and lead nurturing. Get structured flow templates and copy blocks that move subscribers toward conversion.",
    status: "Coming Soon",
    image: "/tools/email.png",
    published: true,
    order: 6,
    isLive: false,
    accent: "#0ea5e9",
    accentLight: "from-[#0ea5e9]/10 to-[#06b6d4]/10",
    popular: false,
    keywords: ["email sequence mapper", "email funnel builder", "email marketing tool", "drip campaign planner"],
    features: [
      "Sequence structure builder",
      "Email copy blocks",
      "Lead nurturing flows",
      "Sales funnel mapping",
    ],
    whoFor: [
      "Marketers",
      "Founders",
      "Email agencies",
      "E-commerce brands",
    ],
    faq: [],
  },
  {
    slug: "conversion-audit-checklist",
    name: "Conversion Audit Checklist",
    category: "Optimization",
    desc: "Identify friction points and missed opportunities across your website.",
    longDesc: "Walk through a structured conversion audit of your website. Identify friction points, weak CTAs, trust signal gaps, and missed opportunities that are costing you customers.",
    status: "Coming Soon",
    image: "/tools/conversion.png",
    published: true,
    order: 7,
    isLive: false,
    accent: "#22c55e",
    accentLight: "from-[#22c55e]/10 to-[#4ade80]/10",
    popular: false,
    keywords: ["conversion audit", "website audit checklist", "CRO checklist", "conversion rate optimisation"],
    features: [
      "Page-by-page audit framework",
      "Friction point identification",
      "CTA and copy review",
      "Mobile experience checks",
    ],
    whoFor: [
      "Website owners",
      "Conversion optimizers",
      "Agencies",
      "E-commerce stores",
    ],
    faq: [],
  },
  {
    slug: "product-launch-planner",
    name: "Product Launch Planner",
    category: "Strategy",
    desc: "Plan launches with structure, clarity, and execution confidence.",
    longDesc: "Structure your entire product launch from pre-launch to post-launch. Get timeline frameworks, warm-up strategies, launch checklists, and post-launch review templates.",
    status: "Coming Soon",
    image: "/tools/launch.png",
    published: true,
    order: 8,
    isLive: false,
    accent: "#f97316",
    accentLight: "from-[#f97316]/10 to-[#fb923c]/10",
    popular: true,
    keywords: ["product launch planner", "launch checklist", "product launch strategy", "go to market planner"],
    features: [
      "Launch timeline builder",
      "Pre-launch checklist",
      "Audience warm-up strategy",
      "Post-launch review framework",
    ],
    whoFor: [
      "Product founders",
      "SaaS teams",
      "Course creators",
      "Marketing leads",
    ],
    faq: [],
  },
    {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    category: "Utilities",
    desc: "Generate QR codes for URLs, text, WiFi, email, phone, SMS and vCards instantly.",
    longDesc: "The free QR Code Generator creates high-quality QR codes for any purpose — websites, WiFi passwords, contact cards, phone numbers, emails and plain text. Customise colours, size and error correction level, then download as PNG or SVG. No sign-up required. Works entirely in your browser.",
    status: "Live",
    image: "/tools/qr-code.png",
    published: true,
    order: 4,
    isLive: true,
    accent: "#f97316",
    accentLight: "from-[#f97316]/10 to-[#fb923c]/10",
    popular: true,
    keywords: [
      "qr code generator",
      "free qr code generator",
      "qr code maker",
      "qr code creator",
      "wifi qr code generator",
      "url to qr code",
      "custom qr code generator",
    ],
    features: [
      "Generate QR codes for URLs, text, WiFi, email, phone, SMS and vCards",
      "Live preview updates as you type",
      "Custom foreground and background colours",
      "Adjustable size from 100px to 1000px",
      "Error correction levels L, M, Q and H",
      "Download as PNG or SVG",
      "Session history of generated codes",
    ],
    whoFor: [
      "Business owners and marketers",
      "Restaurant and retail owners",
      "Event organisers",
      "Developers and agencies",
    ],
    faq: [
      { q: "What is a QR code?", a: "A QR code is a two-dimensional barcode that can be scanned by any smartphone camera to instantly open a URL, connect to WiFi, save a contact, or perform other actions." },
      { q: "Are these QR codes free to use?", a: "Yes. All QR codes generated here are completely free, have no expiry date, and do not require an account. They are yours to use forever." },
      { q: "What is error correction level?", a: "Error correction allows QR codes to be read even if partially damaged or obscured. Level L works for clean surfaces. Level H is best for printed materials that may get dirty or torn." },
      { q: "Can I use these QR codes commercially?", a: "Yes. There are no restrictions on commercial use. You can use QR codes generated here on business cards, menus, packaging, signage or any other material." },
      { q: "What size should I use for printing?", a: "For print materials, use at least 300px with H error correction. For digital screens, 200px is sufficient. The larger the QR code, the easier it is to scan." },
    ],
  },

    {
    slug: "color-palette-generator",
    name: "Color Palette Generator",
    category: "Design",
    desc: "Generate beautiful color palettes instantly from any base color, image, or preset style.",
    longDesc: "The free Color Palette Generator creates professional color palettes for designers, developers, and brand builders. Generate harmonious color schemes from any base color using color theory rules — complementary, analogous, triadic, split-complementary, tetradic and monochromatic. Extract palettes from uploaded images, explore curated presets, check WCAG accessibility contrast ratios, and export in HEX, RGB, HSL, and CSS format.",
    status: "Live",
    image: "/tools/color-palette.png",
    published: true,
    order: 4,
    isLive: true,
    accent: "#ec4899",
    accentLight: "from-[#ec4899]/10 to-[#f43f5e]/10",
    popular: true,
    keywords: [
      "color palette generator",
      "colour palette generator",
      "color scheme generator",
      "color picker tool",
      "brand color generator",
      "color palette from image",
      "complementary color generator",
    ],
    features: [
      "Generate palettes from any base color",
      "6 color harmony rules — complementary, analogous, triadic and more",
      "Extract palette from uploaded image",
      "50+ curated preset palettes",
      "WCAG accessibility contrast checker",
      "Export as HEX, RGB, HSL, CSS variables, Tailwind config",
      "One-click copy for every color and format",
      "Save and name custom palettes",
    ],
    whoFor: [
      "UI/UX designers",
      "Brand designers",
      "Web developers",
      "Marketing teams",
    ],
    faq: [
      { q: "What is a color palette?", a: "A color palette is a curated set of colors used together in a design. A good palette creates visual harmony and guides the viewer's attention effectively." },
      { q: "What is color harmony?", a: "Color harmony refers to how colors work together visually. Complementary colors sit opposite on the color wheel and create contrast. Analogous colors sit next to each other and create unity. Triadic uses three evenly spaced colors for vibrancy." },
      { q: "What is WCAG contrast ratio?", a: "WCAG (Web Content Accessibility Guidelines) defines minimum contrast ratios between text and background colors to ensure readability for people with visual impairments. A ratio of 4.5:1 is required for normal text. 3:1 for large text." },
      { q: "Can I use these colors commercially?", a: "Yes. All colors and palettes generated here are free to use in any commercial project including websites, apps, brand identities, and print materials." },
      { q: "What is the difference between HEX, RGB and HSL?", a: "HEX is a six-character code used in web development. RGB defines colors by red, green and blue values from 0 to 255. HSL defines colors by hue, saturation and lightness — the most intuitive for designers." },
    ],
  },

    {
    slug: "invoice-generator",
    name: "Invoice Generator",
    category: "Business",
    desc: "Create professional invoices instantly and download as PDF. Free, no sign-up required.",
    longDesc: "The free Invoice Generator lets you create professional invoices in seconds. Add your business details, client information, line items, taxes and discounts. Download as PDF or print directly. No account needed, no watermark, completely free. Perfect for freelancers, small businesses and agencies in Nigeria and worldwide.",
    status: "Live",
    image: "/tools/invoice.png",
    published: true,
    order: 4,
    isLive: true,
    accent: "#075a01",
    accentLight: "from-[#075a01]/10 to-[#0a8f01]/10",
    popular: true,
    keywords: [
      "invoice generator",
      "free invoice generator",
      "invoice maker",
      "invoice creator",
      "online invoice generator",
      "pdf invoice generator",
      "freelance invoice generator",
      "invoice generator nigeria",
    ],
    features: [
      "Professional invoice layout with your branding",
      "Add unlimited line items with quantity and rate",
      "Automatic subtotal, tax and discount calculation",
      "Download as PDF or print directly",
      "Save and load invoices in browser",
      "Custom currency support including NGN",
      "Payment terms and notes field",
      "Invoice numbering system",
    ],
    whoFor: [
      "Freelancers and contractors",
      "Small business owners",
      "Agencies and studios",
      "Consultants and service providers",
    ],
    faq: [
      { q: "Is this invoice generator completely free?", a: "Yes. The invoice generator is 100% free with no watermark, no account required, and no hidden fees. You can create and download unlimited invoices." },
      { q: "Can I save my invoice and come back to it?", a: "Yes. Invoices are saved automatically in your browser. You can also save multiple invoices and load them anytime. Note that clearing your browser data will remove saved invoices." },
      { q: "What currencies are supported?", a: "All major currencies are supported including Nigerian Naira (NGN), US Dollar (USD), British Pound (GBP), Euro (EUR), and many more." },
      { q: "How do I download the invoice as PDF?", a: "Click the Download PDF button. The invoice opens in a print-ready view where you can save as PDF using your browser's built-in PDF printer." },
      { q: "Can I add my logo to the invoice?", a: "Yes. Upload your business logo and it will appear at the top of the invoice. Supported formats are PNG, JPG and SVG." },
    ],
  },

    {
    slug: "hashtag-generator",
    name: "Hashtag Generator",
    category: "Social Media",
    desc: "Generate the best hashtags for Instagram, TikTok, Twitter, LinkedIn, YouTube and Facebook instantly.",
    longDesc: "The free Hashtag Generator creates targeted hashtag sets for every major social media platform. Enter your topic, niche or keyword and get hundreds of relevant hashtags grouped by size — small, medium and large — for maximum reach. Build captions with hashtags included, save your favourite sets, and copy everything with one click. No sign-up required.",
    status: "Live",
    image: "/tools/hashtag-generator.png",
    published: true,
    order: 5,
    isLive: true,
    accent: "#e1306c",
    accentLight: "from-[#e1306c]/10 to-[#f77737]/10",
    popular: true,
    keywords: [
      "hashtag generator",
      "instagram hashtag generator",
      "tiktok hashtag generator",
      "hashtag generator free",
      "best hashtags generator",
      "hashtag finder",
      "hashtag creator",
    ],
    features: [
      "Generate hashtags for Instagram, TikTok, Twitter, LinkedIn, YouTube and Facebook",
      "Hashtags grouped by size — small, medium and large",
      "Platform-specific hashtag limits and strategy",
      "Caption builder with hashtags included",
      "One-click copy for all hashtags",
      "Save favourite hashtag sets",
      "Hashtag count and character limit tracker",
    ],
    whoFor: [
      "Content creators and influencers",
      "Social media managers",
      "Small business owners",
      "Digital marketing agencies",
    ],
    faq: [
      { q: "How many hashtags should I use on Instagram?", a: "Instagram allows up to 30 hashtags per post. The best strategy is to use 10–15 hashtags — a mix of small (under 500K posts), medium (500K–2M posts) and large (over 2M posts) for maximum reach." },
      { q: "How many hashtags should I use on TikTok?", a: "TikTok recommends 3–5 hashtags per video. Using too many can actually reduce reach. Focus on 2–3 niche hashtags and 1–2 trending ones." },
      { q: "Do hashtags work on LinkedIn?", a: "Yes. LinkedIn hashtags work well but use fewer — 3–5 is ideal. LinkedIn users respond better to professional and industry-specific hashtags than trending ones." },
      { q: "What is the difference between small, medium and large hashtags?", a: "Small hashtags have under 500K posts — less competition, more likely to rank. Medium have 500K–2M posts — good balance. Large have over 2M — high competition but high reach if your content performs well." },
      { q: "Can I save my hashtag sets?", a: "Yes. Click Save Set on any generated hashtag group and it will be stored in your browser for future use. Your sets are never sent to any server." },
    ],
  },
];