export const tools = [
  {
    slug: "seo-meta-tag-generator",
    name: "SEO Meta Tag Generator",
    category: "SEO",
    desc: "Generate perfect SEO meta titles and descriptions with a live Google preview and real-time scoring.",
    longDesc: "The SEO Meta Tag Generator helps website owners, bloggers, and marketers create optimised meta titles and descriptions that rank higher on Google. Get real-time character count validation, keyword density checking, live Google search preview, and instant HTML output ready to paste into your website.",
    status: "Live",
    image: "/tools/seo-planner.png",
    published: true,
    order: 1,
    isLive: true,
    accent: "#075a01",
    accentLight: "from-[#075a01]/10 to-[#0a8f01]/10",
    popular: true,
    keywords: ["seo meta tag generator", "meta description generator", "meta title generator", "seo title generator", "google meta tags", "meta tag creator"],
    features: [
      "Live Google desktop and mobile search preview",
      "Real-time character count with colour validation",
      "17-point SEO scoring engine",
      "Keyword density and position checking",
      "Twitter and Facebook OG preview",
      "One-click HTML copy to clipboard",
      "Download tags as .txt file",
    ],
    whoFor: [
      "SEO specialists",
      "Content writers",
      "Business owners",
      "Bloggers and publishers",
    ],
    faq: [
      { q: "What is a meta tag?", a: "A meta tag is an HTML element that provides information about a webpage to search engines and social media platforms. The two most important are the title tag and meta description." },
      { q: "How long should a meta title be?", a: "Between 30 and 60 characters. Google truncates titles longer than 60 characters in search results." },
      { q: "How long should a meta description be?", a: "Between 70 and 160 characters. Longer descriptions get cut off in Google search results." },
      { q: "Does meta description affect rankings?", a: "Not directly, but it affects click-through rate which signals quality to Google and indirectly improves rankings." },
    ],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    category: "Writing",
    desc: "Count words, characters, sentences and paragraphs instantly with readability scoring and keyword density analysis.",
    longDesc: "The Word Counter tool gives writers, students, SEO specialists and content creators a complete text analysis suite. Get instant word count, character count, reading time, speaking time, readability score, keyword density, passive voice detection, and platform character limit checks all in one place.",
    status: "Live",
    image: "/tools/word-counter.png",
    published: true,
    order: 2,
    isLive: true,
    accent: "#0ea5e9",
    accentLight: "from-[#0ea5e9]/10 to-[#06b6d4]/10",
    popular: true,
    keywords: ["word counter", "character counter", "word count tool", "online word counter", "count words online", "text analyser"],
    features: [
      "Real-time word and character count",
      "Reading time and speaking time estimate",
      "Flesch readability score",
      "Keyword density analysis",
      "Passive voice and adverb detection",
      "Platform character limit checker",
      "Auto-save, text cleaner, and case converter",
      "Text diff comparison and auto summariser",
    ],
    whoFor: [
      "Writers and bloggers",
      "Students and academics",
      "SEO content creators",
      "Social media managers",
    ],
    faq: [
      { q: "How accurate is the word counter?", a: "The counter uses the same word boundary detection as professional editors — splitting on spaces, punctuation, and line breaks. It is accurate to the word." },
      { q: "What is a good readability score?", a: "For web content, aim for a Flesch Reading Ease score of 60 or above. Blog posts and articles should target 60–70. Academic content naturally scores lower." },
      { q: "What is keyword density?", a: "Keyword density is how often a keyword appears as a percentage of total words. The ideal range is 1–2.5%. Over 3% risks being seen as keyword stuffing by Google." },
      { q: "Does the tool save my text?", a: "Yes. Auto-save is on by default and saves your text to your browser every 1.5 seconds. Your text is never sent to any server." },
    ],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    category: "Security",
    desc: "Generate strong, secure, random passwords instantly with full control over length and character types.",
    longDesc: "The Password Generator creates cryptographically strong passwords using your browser's built-in secure random number generator. Choose password length, include uppercase, lowercase, numbers and symbols, check password strength in real time, and copy instantly. No data is ever sent to a server.",
    status: "Live",
    image: "/tools/password-generator.png",
    published: true,
    order: 3,
    isLive: true,
    accent: "#8b5cf6",
    accentLight: "from-[#8b5cf6]/10 to-[#a78bfa]/10",
    popular: true,
    keywords: ["password generator", "strong password generator", "random password generator", "secure password generator", "password creator", "password maker"],
    features: [
      "Cryptographically secure random generation",
      "Adjustable length from 4 to 128 characters",
      "Toggle uppercase, lowercase, numbers, symbols",
      "Real-time password strength scoring",
      "Bulk generate up to 10 passwords at once",
      "One-click copy to clipboard",
      "Password history within session",
      "Entropy calculation",
    ],
    whoFor: [
      "Everyone with online accounts",
      "IT administrators",
      "Developers and engineers",
      "Business owners",
    ],
    faq: [
      { q: "Is this password generator secure?", a: "Yes. Passwords are generated using window.crypto.getRandomValues() which is the same cryptographic randomness used by browsers for SSL. No passwords are stored or transmitted." },
      { q: "How long should my password be?", a: "At minimum 12 characters. For critical accounts like banking and email, use 16–24 characters with all character types enabled." },
      { q: "Are the generated passwords saved anywhere?", a: "No. Everything runs in your browser. Nothing is sent to any server. The session history clears when you close the tab." },
      { q: "What makes a password strong?", a: "Length, randomness, and character variety. A 16-character password with uppercase, lowercase, numbers and symbols has over 85 bits of entropy — effectively uncrackable by brute force." },
    ],
  },
  {
    slug: "ai-landing-page-generator",
    name: "AI Landing Page Generator",
    category: "Marketing",
    desc: "Generate high-converting landing page structures and copy with clarity and speed.",
    longDesc: "Plan and structure high-converting landing pages using proven frameworks. Get section-by-section guidance, headline formulas, CTA logic, and value proposition structure without the guesswork.",
    status: "Coming Soon",
    image: "/tools/ai-landing.png",
    published: true,
    order: 4,
    isLive: false,
    accent: "#ff914d",
    accentLight: "from-[#ff914d]/10 to-[#ff6b1a]/10",
    popular: true,
    keywords: ["landing page generator", "ai landing page", "landing page builder", "conversion landing page"],
    features: [
      "AI-generated landing page structure",
      "Conversion-focused hero and CTA sections",
      "Clear value-proposition messaging",
      "Export-ready copy and layout outline",
    ],
    whoFor: [
      "Startup founders",
      "Product launches",
      "Marketing campaigns",
      "Client landing pages",
    ],
    faq: [],
  },
  {
    slug: "brand-identity-builder",
    name: "Brand Identity Builder",
    category: "Design",
    desc: "Create a consistent brand system with colors, typography, and visual direction.",
    longDesc: "Define your brand colours, typography pairings, and visual direction in one place. Get consistency rules and guidance to apply across all your brand touchpoints.",
    status: "In Development",
    image: "/tools/brand-identity.png",
    published: true,
    order: 5,
    isLive: false,
    accent: "#8b5cf6",
    accentLight: "from-[#8b5cf6]/10 to-[#a78bfa]/10",
    popular: false,
    keywords: ["brand identity builder", "brand system generator", "brand color generator", "typography tool"],
    features: [
      "Brand color system generation",
      "Typography pairing suggestions",
      "Visual identity direction",
      "Consistency rules and guidance",
    ],
    whoFor: [
      "New brands",
      "Rebrands",
      "Designers",
      "Client brand systems",
    ],
    faq: [],
  },
  {
    slug: "email-sequence-mapper",
    name: "Email Sequence Mapper",
    category: "Email Marketing",
    desc: "Structure email flows that improve engagement, retention, and conversion.",
    longDesc: "Map out complete email sequences for onboarding, sales funnels, and lead nurturing. Get structured flow templates and copy blocks that move subscribers toward conversion.",
    status: "Coming Soon",
    image: "/tools/email.png",
    published: true,
    order: 6,
    isLive: false,
    accent: "#0ea5e9",
    accentLight: "from-[#0ea5e9]/10 to-[#06b6d4]/10",
    popular: false,
    keywords: ["email sequence mapper", "email funnel builder", "email marketing tool", "drip campaign planner"],
    features: [
      "Sequence structure builder",
      "Email copy blocks",
      "Lead nurturing flows",
      "Sales funnel mapping",
    ],
    whoFor: [
      "Marketers",
      "Founders",
      "Email agencies",
      "E-commerce brands",
    ],
    faq: [],
  },
  {
    slug: "conversion-audit-checklist",
    name: "Conversion Audit Checklist",
    category: "Optimization",
    desc: "Identify friction points and missed opportunities across your website.",
    longDesc: "Walk through a structured conversion audit of your website. Identify friction points, weak CTAs, trust signal gaps, and missed opportunities that are costing you customers.",
    status: "Coming Soon",
    image: "/tools/conversion.png",
    published: true,
    order: 7,
    isLive: false,
    accent: "#22c55e",
    accentLight: "from-[#22c55e]/10 to-[#4ade80]/10",
    popular: false,
    keywords: ["conversion audit", "website audit checklist", "CRO checklist", "conversion rate optimisation"],
    features: [
      "Page-by-page audit framework",
      "Friction point identification",
      "CTA and copy review",
      "Mobile experience checks",
    ],
    whoFor: [
      "Website owners",
      "Conversion optimizers",
      "Agencies",
      "E-commerce stores",
    ],
    faq: [],
  },
  {
    slug: "product-launch-planner",
    name: "Product Launch Planner",
    category: "Strategy",
    desc: "Plan launches with structure, clarity, and execution confidence.",
    longDesc: "Structure your entire product launch from pre-launch to post-launch. Get timeline frameworks, warm-up strategies, launch checklists, and post-launch review templates.",
    status: "Coming Soon",
    image: "/tools/launch.png",
    published: true,
    order: 8,
    isLive: false,
    accent: "#f97316",
    accentLight: "from-[#f97316]/10 to-[#fb923c]/10",
    popular: true,
    keywords: ["product launch planner", "launch checklist", "product launch strategy", "go to market planner"],
    features: [
      "Launch timeline builder",
      "Pre-launch checklist",
      "Audience warm-up strategy",
      "Post-launch review framework",
    ],
    whoFor: [
      "Product founders",
      "SaaS teams",
      "Course creators",
      "Marketing leads",
    ],
    faq: [],
  },
];