"use client";

import Image from "next/image";
import Link from "next/link";
import {
  ArrowRight,
  Sparkles,
  Star,
  Eye,
  Link as LinkIcon,
  Leaf,
  Briefcase,
  Rocket,
  Award,
  Target,
  Layers,
  Wrench,
  Lightbulb,
  Zap,
  Palette,
  Building2,
  Users,
  TrendingUp,
  Settings,
  Mail,
  Phone,
  MessageCircle,
  ChevronRight,
  FileText,
  Globe,
  CheckCircle2,
  Code2,
  Search,
  PenTool,
  Heart,
  Crown,
  ShieldCheck,
} from "lucide-react";

const founder = {
  name: "Bashir Ismail",
  alias: "Fancy",
  role: "Founder & Digital Architect",
  image: "/images/founder.jpg",
  bio: [
    "Bashir Ismail, widely known as Fancy, is the founder of Fancy Digitals — a premium digital studio focused on building calm, scalable, and intentional digital systems.",
    "With years of hands-on experience across design, frontend engineering, and digital strategy, he helps businesses replace chaos with structure and long-term clarity.",
  ],
};

const experience = [
  { years: 11, label: "Digital Experience", Icon: Lightbulb },
  { years: 7, label: "Frontend Engineering", Icon: Code2 },
  { years: 5, label: "Product Design", Icon: Palette },
  { years: 4, label: "System Architecture", Icon: Layers },
  { years: 3, label: "Agency Leadership", Icon: Crown },
];

const aiTools = [
  {
    name: "AI Landing Page Generator",
    desc: "Build full landing pages in 60 seconds with AI",
    href: "/free-ai-landing-page-generator",
    Icon: Globe,
    color: "#075a01",
  },
  {
    name: "AI Resume Builder",
    desc: "ATS-optimized resumes generated by AI",
    href: "/free-ai-resume-builder",
    Icon: FileText,
    color: "#0369a1",
  },
  {
    name: "AI Cover Letter Generator",
    desc: "Tailored cover letters for any job",
    href: "/free-ai-cover-letter",
    Icon: PenTool,
    color: "#7c3aed",
  },
  {
    name: "Free Utility Tools",
    desc: "QR codes, invoices, password generator and more",
    href: "/tools",
    Icon: Wrench,
    color: "#f97316",
  },
];

const expertise = [
  { label: "Web Design", Icon: Palette },
  { label: "Frontend Engineering", Icon: Code2 },
  { label: "AI Tools Development", Icon: Sparkles },
  { label: "Landing Page Design", Icon: Globe },
  { label: "SEO Strategy", Icon: Search },
  { label: "Brand Identity", Icon: Star },
  { label: "Product Design", Icon: PenTool },
  { label: "Digital Strategy", Icon: Target },
];

const values = [
  {
    title: "Clarity over noise",
    description:
      "Every decision is guided by simplicity, purpose, and long-term usefulness — not trends or vanity.",
    Icon: Eye,
  },
  {
    title: "Systems thinking",
    description:
      "Digital work is treated as an interconnected system, not isolated deliverables.",
    Icon: LinkIcon,
  },
  {
    title: "Calm execution",
    description:
      "Workflows are designed to reduce friction, stress, and unnecessary complexity.",
    Icon: Leaf,
  },
];

const clientTypes = [
  { text: "Founders building long-term digital products", Icon: Target },
  { text: "Growing brands needing structure and clarity", Icon: TrendingUp },
  { text: "Agencies seeking reliable technical execution", Icon: Users },
  { text: "Teams replacing fragile or overbuilt systems", Icon: Settings },
];

const journey = [
  {
    year: "2015",
    title: "Started in Digital",
    desc: "Began exploring web design and development as a self-taught enthusiast.",
    Icon: Leaf,
  },
  {
    year: "2019",
    title: "First Agency Role",
    desc: "Joined a digital agency, honing skills in client work and project delivery.",
    Icon: Briefcase,
  },
  {
    year: "2020",
    title: "Freelance Journey",
    desc: "Launched independent practice, working directly with founders and brands.",
    Icon: Rocket,
  },
  {
    year: "2022",
    title: "Founded Fancy Digitals",
    desc: "Established the studio to deliver premium, systems-focused digital work.",
    Icon: Award,
  },
  {
    year: "2024",
    title: "Launched AI Tools Suite",
    desc: "Built AI Resume Builder, Cover Letter, and Landing Page Generator — used by thousands.",
    Icon: Sparkles,
  },
];

const stats = [
  { value: "50+", label: "Happy Clients", Icon: Users },
  { value: "10+", label: "Years Experience", Icon: Award },
  { value: "100+", label: "Projects Delivered", Icon: Briefcase },
  { value: "5.0", label: "Average Rating", Icon: Star },
];

const faqs = [
  {
    q: "Who is Bashir Ismail?",
    a: "Bashir Ismail, known as Fancy, is the founder of Fancy Digitals — a Nigerian digital agency building AI tools, landing pages, resumes, and premium web systems for businesses worldwide.",
  },
  {
    q: "What is Fancy Digitals?",
    a: "Fancy Digitals is a digital agency based in Lagos, Nigeria, that builds AI-powered tools, custom websites, and provides SEO, branding, and digital strategy services to clients across Africa and globally.",
  },
  {
    q: "What AI tools has Bashir built?",
    a: "Bashir has built AI Resume Builder, AI Cover Letter Generator, AI Landing Page Generator, and a full suite of free productivity tools including QR Code Generator, Password Generator, and Invoice Maker.",
  },
  {
    q: "How do I work with Bashir Ismail?",
    a: "You can reach out through the Fancy Digitals contact page, call +234 904 554 7761, or message on WhatsApp at +234 903 436 0785 to discuss your project.",
  },
  {
    q: "Where is Fancy Digitals based?",
    a: "Fancy Digitals is based in Lagos, Nigeria, and serves clients across Nigeria, Africa, and globally.",
  },
];

export default function AboutClient() {
  return (
    <main className="relative min-h-screen overflow-hidden bg-gradient-to-b from-gray-50 via-white to-gray-50">
      {/* Background Decorations */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute -left-40 -top-40 h-[600px] w-[600px] rounded-full bg-[#075a01]/10 blur-[120px]" />
        <div className="absolute -right-40 top-1/4 h-[500px] w-[500px] rounded-full bg-[#ff914d]/10 blur-[100px]" />
        <div className="absolute bottom-1/3 left-1/4 h-[400px] w-[400px] rounded-full bg-[#075a01]/5 blur-[80px]" />
        <div className="absolute -bottom-40 right-1/4 h-[500px] w-[500px] rounded-full bg-[#ff914d]/8 blur-[100px]" />
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#00000005_1px,transparent_1px),linear-gradient(to_bottom,#00000005_1px,transparent_1px)] bg-[size:40px_40px]" />
      </div>

      {/* ============ HERO ============ */}
      <section className="relative px-5 pb-16 pt-24 md:px-10 md:pt-32">
        <div className="mx-auto max-w-7xl">
          <nav className="mb-10 flex justify-center">
            <div className="inline-flex items-center gap-2 rounded-full border border-gray-200 bg-white px-5 py-2.5 shadow-sm">
              <Link href="/" className="text-sm text-gray-500 hover:text-[#075a01] transition-colors">Home</Link>
              <ChevronRight className="h-4 w-4 text-gray-300" />
              <span className="text-sm font-semibold text-gray-900">About</span>
            </div>
          </nav>

          <div className="grid items-center gap-12 lg:grid-cols-2 lg:gap-20">
            {/* Text */}
            <div className="order-2 text-center lg:order-1 lg:text-left">
              <div className="mb-5 inline-flex items-center gap-2 rounded-full bg-[#075a01]/10 px-4 py-2">
                <Sparkles className="h-4 w-4 text-[#075a01]" />
                <span className="text-xs font-bold uppercase tracking-wider text-[#075a01]">
                  Founder · Fancy Digitals
                </span>
              </div>

              <h1 className="text-4xl font-bold leading-tight tracking-tight text-gray-900 md:text-5xl lg:text-6xl">
                <span className="block">Meet</span>
                <span className="mt-2 block bg-gradient-to-r from-[#075a01] via-[#ff914d] to-[#075a01] bg-clip-text text-transparent">
                  {founder.name}
                </span>
                <span className="mt-2 block text-2xl font-medium text-gray-500 md:text-3xl">
                  a.k.a &quot;{founder.alias}&quot;
                </span>
              </h1>

              <div className="mx-auto mt-8 max-w-xl space-y-4 lg:mx-0">
                {founder.bio.map((paragraph, idx) => (
                  <p key={idx} className="text-base leading-relaxed text-gray-600 md:text-lg">
                    {paragraph}
                  </p>
                ))}
              </div>

              <div className="mt-10 flex flex-col items-center gap-3 sm:flex-row lg:justify-start">
                <Link
                  href="/contact"
                  className="group inline-flex w-full sm:w-auto items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#075a01] to-[#0a8f01] px-8 py-4 font-bold text-white shadow-lg shadow-[#075a01]/25 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"
                >
                  Work With Me
                  <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" />
                </Link>
                <Link
                  href="/portfolio"
                  className="group inline-flex w-full sm:w-auto items-center justify-center gap-2 rounded-xl border-2 border-gray-200 bg-white px-8 py-4 font-bold text-gray-700 shadow-sm transition-all hover:-translate-y-1 hover:border-[#075a01]/30 hover:shadow-lg"
                >
                  View My Work
                </Link>
              </div>

              <div className="mt-8 flex flex-wrap items-center justify-center gap-6 lg:justify-start">
                <div className="flex items-center gap-2">
                  <div className="flex -space-x-2">
                    {[1, 2, 3, 4].map((i) => (
                      <div key={i} className="h-8 w-8 rounded-full border-2 border-white bg-gradient-to-br from-gray-200 to-gray-300" />
                    ))}
                  </div>
                  <span className="text-sm text-gray-500">50+ happy clients</span>
                </div>
                <div className="flex items-center gap-1">
                  {[1, 2, 3, 4, 5].map((i) => (
                    <Star key={i} className="h-4 w-4 fill-[#ff914d] text-[#ff914d]" />
                  ))}
                  <span className="ml-1 text-sm text-gray-500">5.0 rating</span>
                </div>
              </div>
            </div>

            {/* Image */}
            <div className="order-1 flex justify-center lg:order-2">
              <div className="relative">
                <div className="absolute -inset-8 rounded-full border-2 border-dashed border-[#075a01]/20 opacity-50" />
                <div className="absolute -inset-16 rounded-full border border-dashed border-[#ff914d]/10 opacity-30" />

                <div className="relative aspect-[5/6] w-72 overflow-hidden rounded-[2.5rem] border-4 border-white bg-gradient-to-br from-[#075a01]/10 to-[#ff914d]/10 shadow-2xl sm:w-80 md:w-96 lg:w-[400px]">
                  <Image
                    src={founder.image}
                    alt="Bashir Ismail (Fancy), Founder of Fancy Digitals"
                    fill
                    priority
                    className="object-cover object-center"
                    sizes="(max-width: 640px) 288px, (max-width: 1024px) 384px, 400px"
                  />
                </div>

                <div className="absolute -bottom-4 -right-4 rounded-2xl border-2 border-white bg-white px-5 py-4 shadow-xl md:-right-8">
                  <p className="bg-gradient-to-r from-[#075a01] to-[#ff914d] bg-clip-text text-3xl font-bold text-transparent">10+</p>
                  <p className="text-xs font-medium text-gray-500">Years Exp.</p>
                </div>

                <div className="absolute -left-4 top-1/4 rounded-2xl border-2 border-white bg-white p-3 shadow-xl md:-left-8">
                  <Sparkles className="h-6 w-6 text-[#ff914d]" />
                </div>

                <div className="absolute -right-2 top-8 rounded-xl border-2 border-white bg-white p-2 shadow-lg">
                  <Crown className="h-5 w-5 text-[#075a01]" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ============ STATS STRIP ============ */}
      <section className="relative py-12 md:py-16">
        <div className="absolute inset-0 bg-gradient-to-r from-[#075a01] via-[#0a8f01] to-[#075a01]" />
        <div className="relative mx-auto max-w-7xl px-5 md:px-10">
          <div className="grid grid-cols-2 gap-6 md:grid-cols-4 md:gap-4">
            {stats.map(({ value, label, Icon }) => (
              <div key={label} className="text-center">
                <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-2xl bg-white/15 backdrop-blur-sm">
                  <Icon className="h-6 w-6 text-white" />
                </div>
                <p className="text-3xl font-bold text-white md:text-4xl">{value}</p>
                <p className="mt-1 text-xs font-semibold text-white/80 md:text-sm">{label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ============ EXPERIENCE ============ */}
      <section className="relative px-5 py-20 md:px-10 md:py-24">
        <div className="mx-auto max-w-7xl">
          <div className="mb-12 text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#ff914d]/10 px-4 py-2">
              <Award className="h-4 w-4 text-[#ff914d]" />
              <span className="text-xs font-bold uppercase tracking-wider text-[#ff914d]">Experience</span>
            </div>
            <h2 className="text-3xl font-bold text-gray-900 md:text-4xl">
              Years of <span className="text-[#075a01]">deep expertise</span>
            </h2>
          </div>

          <div className="grid grid-cols-2 gap-3 md:grid-cols-5">
            {experience.map(({ years, label, Icon }) => (
              <div key={label} className="group rounded-2xl border-2 border-gray-100 bg-white p-5 text-center shadow-sm transition-all hover:-translate-y-1 hover:border-[#075a01]/20 hover:shadow-lg">
                <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-[#075a01]/10 to-[#ff914d]/10 transition group-hover:from-[#075a01] group-hover:to-[#ff914d]">
                  <Icon className="h-5 w-5 text-[#075a01] transition group-hover:text-white" />
                </div>
                <p className="text-3xl font-bold text-gray-900">
                  {years}<span className="text-[#ff914d]">+</span>
                </p>
                <p className="mt-1 text-xs font-semibold text-gray-500">{label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ============ AI TOOLS BY BASHIR ============ */}
      <section className="relative px-5 pb-20 md:px-10">
        <div className="mx-auto max-w-7xl">
          <div className="mb-12 text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#075a01]/10 px-4 py-2">
              <Sparkles className="h-4 w-4 text-[#075a01]" />
              <span className="text-xs font-bold uppercase tracking-wider text-[#075a01]">Built by Bashir</span>
            </div>
            <h2 className="text-3xl font-bold text-gray-900 md:text-4xl">
              AI tools used by <span className="text-[#075a01]">thousands</span>
            </h2>
            <p className="mx-auto mt-3 max-w-xl text-gray-600">
              Free, powerful tools built from scratch — designed to solve real problems for real people.
            </p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {aiTools.map(({ name, desc, href, Icon, color }) => (
              <Link
                key={name}
                href={href}
                className="group relative overflow-hidden rounded-2xl border-2 border-gray-100 bg-white p-6 shadow-sm transition-all hover:-translate-y-1 hover:shadow-xl"
              >
                <div
                  className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl transition group-hover:scale-110"
                  style={{ background: `${color}15`, color }}
                >
                  <Icon className="h-6 w-6" />
                </div>
                <h3 className="mb-2 font-bold text-gray-900">{name}</h3>
                <p className="text-sm text-gray-500 leading-relaxed">{desc}</p>
                <div className="mt-4 flex items-center gap-1 text-xs font-bold" style={{ color }}>
                  Try it free
                  <ArrowRight className="h-3 w-3 transition-transform group-hover:translate-x-1" />
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* ============ JOURNEY ============ */}
      <section className="relative px-5 py-20 md:px-10 md:py-24">
        <div className="mx-auto max-w-7xl">
          <div className="mb-16 text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#ff914d]/10 px-4 py-2">
              <TrendingUp className="h-4 w-4 text-[#ff914d]" />
              <span className="text-xs font-bold uppercase tracking-wider text-[#ff914d]">My Journey</span>
            </div>
            <h2 className="text-3xl font-bold text-gray-900 md:text-4xl">
              From curiosity to <span className="text-[#075a01]">expertise</span>
            </h2>
          </div>

          <div className="relative">
            <div className="absolute left-1/2 top-0 hidden h-full w-0.5 -translate-x-1/2 bg-gradient-to-b from-[#075a01] via-[#ff914d] to-[#075a01] md:block" />

            <div className="space-y-8 md:space-y-12">
              {journey.map(({ year, title, desc, Icon }, idx) => (
                <div
                  key={year}
                  className={`relative flex flex-col items-center gap-6 md:flex-row ${
                    idx % 2 === 0 ? "md:flex-row" : "md:flex-row-reverse"
                  }`}
                >
                  <div className={`w-full md:w-[calc(50%-40px)] ${idx % 2 === 0 ? "md:text-right" : "md:text-left"}`}>
                    <div className="group rounded-2xl border-2 border-gray-100 bg-white p-6 shadow-sm transition-all hover:-translate-y-1 hover:border-[#075a01]/20 hover:shadow-xl">
                      <span className="mb-2 inline-block rounded-full bg-[#075a01]/10 px-3 py-1 text-xs font-bold text-[#075a01]">{year}</span>
                      <h3 className="mb-2 text-lg font-bold text-gray-900">{title}</h3>
                      <p className="text-sm text-gray-600">{desc}</p>
                    </div>
                  </div>

                  <div className="relative z-10 flex h-16 w-16 shrink-0 items-center justify-center rounded-full border-4 border-white bg-gradient-to-br from-[#075a01] to-[#ff914d] shadow-lg">
                    <Icon className="h-6 w-6 text-white" />
                  </div>

                  <div className="hidden w-[calc(50%-40px)] md:block" />
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ============ EXPERTISE GRID ============ */}
      <section className="relative px-5 pb-20 md:px-10">
        <div className="mx-auto max-w-5xl">
          <div className="mb-10 text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#075a01]/10 px-4 py-2">
              <ShieldCheck className="h-4 w-4 text-[#075a01]" />
              <span className="text-xs font-bold uppercase tracking-wider text-[#075a01]">Core Expertise</span>
            </div>
            <h2 className="text-3xl font-bold text-gray-900 md:text-4xl">
              Skills that <span className="text-[#075a01]">deliver</span>
            </h2>
          </div>

          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            {expertise.map(({ label, Icon }) => (
              <div key={label} className="group flex flex-col items-center gap-2 rounded-xl border-2 border-gray-100 bg-white p-4 text-center shadow-sm transition-all hover:-translate-y-1 hover:border-[#075a01]/20 hover:shadow-md">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#075a01]/10 transition group-hover:bg-[#075a01]">
                  <Icon className="h-5 w-5 text-[#075a01] transition group-hover:text-white" />
                </div>
                <p className="text-xs font-bold text-gray-700">{label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ============ PHILOSOPHY ============ */}
      <section className="relative px-5 pb-20 md:px-10">
        <div className="mx-auto max-w-7xl">
          <div className="overflow-hidden rounded-3xl border border-gray-100 bg-white p-8 shadow-xl md:p-12">
            <div className="grid items-center gap-12 lg:grid-cols-2">
              <div className="relative flex justify-center">
                <div className="relative w-full max-w-sm">
                  <div className="absolute -inset-4 rounded-3xl bg-gradient-to-br from-[#075a01]/10 to-[#ff914d]/10 blur-xl" />
                  <div className="relative rounded-2xl border border-gray-100 bg-gradient-to-br from-gray-50 to-white p-8 shadow-lg">
                    <div className="space-y-6">
                      {[
                        { title: "Listen First", desc: "Understand the real problem", Icon: Heart, gradient: "from-[#075a01] to-[#0a8f01]" },
                        { title: "Understand Deeply", desc: "Connect all the dots", Icon: Target, gradient: "from-[#ff914d] to-[#ff6b1a]" },
                        { title: "Execute Calmly", desc: "Deliver with precision", Icon: Rocket, gradient: "from-[#075a01] to-[#ff914d]" },
                      ].map(({ title, desc, Icon, gradient }, i) => (
                        <div key={title}>
                          <div className="flex items-center gap-4">
                            <div className={`flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br ${gradient} shadow-lg`}>
                              <Icon className="h-6 w-6 text-white" />
                            </div>
                            <div>
                              <p className="font-bold text-gray-900">{title}</p>
                              <p className="text-sm text-gray-500">{desc}</p>
                            </div>
                          </div>
                          {i < 2 && <div className="ml-7 mt-4 h-6 w-px bg-gray-200" />}
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              <div>
                <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#075a01]/10 px-4 py-2">
                  <Lightbulb className="h-4 w-4 text-[#075a01]" />
                  <span className="text-xs font-bold uppercase tracking-wider text-[#075a01]">My Philosophy</span>
                </div>
                <h2 className="text-3xl font-bold text-gray-900 md:text-4xl">
                  How I approach <span className="bg-gradient-to-r from-[#075a01] to-[#ff914d] bg-clip-text text-transparent">digital work</span>
                </h2>
                <div className="mt-6 space-y-4 text-gray-600">
                  <p>
                    My approach begins with <strong className="text-gray-900">listening</strong>. The quality of any solution is directly tied to how well the problem is understood.
                  </p>
                  <p>
                    This allows complex ideas to be translated into <strong className="text-gray-900">clean, usable, and scalable</strong> digital systems.
                  </p>
                  <p>
                    My agility across multiple disciplines reduces friction, shortens feedback loops, and ensures strategy, design, and execution remain <strong className="text-gray-900">aligned from start to finish</strong>.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ============ VALUES ============ */}
      <section className="relative px-5 pb-20 md:px-10">
        <div className="mx-auto max-w-7xl">
          <div className="mb-12 text-center">
            <h2 className="text-3xl font-bold text-gray-900 md:text-4xl">
              What <span className="text-[#075a01]">drives</span> my work
            </h2>
          </div>

          <div className="grid gap-6 md:grid-cols-3">
            {values.map(({ title, description, Icon }) => (
              <div key={title} className="group relative overflow-hidden rounded-3xl border-2 border-gray-100 bg-white p-8 shadow-sm transition-all hover:-translate-y-2 hover:border-[#075a01]/20 hover:shadow-xl">
                <div className="mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-[#075a01]/10 to-[#ff914d]/10 transition group-hover:from-[#075a01] group-hover:to-[#ff914d]">
                  <Icon className="h-6 w-6 text-[#075a01] transition group-hover:text-white" />
                </div>
                <h3 className="mb-3 text-xl font-bold text-gray-900">{title}</h3>
                <p className="leading-relaxed text-gray-600">{description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ============ CLIENT TYPES ============ */}
      <section className="relative px-5 pb-20 md:px-10">
        <div className="mx-auto max-w-7xl">
          <div className="grid items-center gap-12 lg:grid-cols-2">
            <div>
              <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#075a01]/10 px-4 py-2">
                <Users className="h-4 w-4 text-[#075a01]" />
                <span className="text-xs font-bold uppercase tracking-wider text-[#075a01]">Ideal Clients</span>
              </div>
              <h2 className="text-3xl font-bold text-gray-900 md:text-4xl">
                Who I love <span className="bg-gradient-to-r from-[#075a01] to-[#ff914d] bg-clip-text text-transparent">working with</span>
              </h2>
              <p className="mt-4 text-gray-600">
                I partner with businesses and individuals who value intentional, long-term digital growth over quick fixes.
              </p>
              <Link href="/contact" className="group mt-6 inline-flex items-center gap-2 font-semibold text-[#075a01] hover:text-[#0a8f01]">
                Let&apos;s see if we&apos;re a fit
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
              </Link>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              {clientTypes.map(({ text, Icon }) => (
                <div key={text} className="group flex items-start gap-4 rounded-2xl border-2 border-gray-100 bg-white p-5 shadow-sm transition-all hover:-translate-y-1 hover:border-[#075a01]/20 hover:shadow-lg">
                  <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-[#075a01]/10 to-[#ff914d]/10 transition group-hover:from-[#075a01] group-hover:to-[#ff914d]">
                    <Icon className="h-5 w-5 text-[#075a01] transition group-hover:text-white" />
                  </div>
                  <p className="text-sm font-medium text-gray-700 group-hover:text-gray-900">{text}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ============ FAQ ============ */}
      <section className="relative px-5 pb-20 md:px-10">
        <div className="mx-auto max-w-3xl">
          <div className="mb-10 text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#075a01]/10 px-4 py-2">
              <MessageCircle className="h-4 w-4 text-[#075a01]" />
              <span className="text-xs font-bold uppercase tracking-wider text-[#075a01]">FAQs</span>
            </div>
            <h2 className="text-3xl font-bold text-gray-900 md:text-4xl">
              Common <span className="text-[#075a01]">questions</span>
            </h2>
          </div>

          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <details key={i} className="group rounded-2xl border-2 border-gray-100 bg-white p-5 shadow-sm transition-all hover:border-[#075a01]/20 hover:shadow-md">
                <summary className="flex cursor-pointer items-center justify-between gap-4 list-none">
                  <h3 className="font-bold text-gray-900">{faq.q}</h3>
                  <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-gray-100 transition group-open:rotate-45 group-open:bg-[#075a01]">
                    <span className="text-lg font-bold text-gray-600 transition group-open:text-white">+</span>
                  </div>
                </summary>
                <p className="mt-4 text-sm leading-relaxed text-gray-600">{faq.a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* ============ FINAL CTA ============ */}
      <section className="relative px-5 pb-20 md:px-10">
        <div className="mx-auto max-w-7xl">
          <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#075a01] to-[#0a8f01] p-10 shadow-2xl md:p-16">
            <div className="pointer-events-none absolute -right-20 -top-20 h-60 w-60 rounded-full bg-white/10 blur-3xl" />
            <div className="pointer-events-none absolute -bottom-20 -left-20 h-60 w-60 rounded-full bg-[#ff914d]/20 blur-3xl" />

            <div className="relative grid items-center gap-10 md:grid-cols-[1fr_auto]">
              <div className="text-center md:text-left">
                <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-white/20 px-4 py-2 backdrop-blur-sm">
                  <Mail className="h-4 w-4 text-white" />
                  <span className="text-xs font-bold uppercase tracking-wider text-white">A note from me</span>
                </div>
                <h2 className="text-3xl font-bold text-white md:text-4xl">
                  Let&apos;s build something
                  <span className="block text-[#ffed4e]">remarkable together</span>
                </h2>
                <p className="mx-auto mt-6 max-w-xl text-lg text-white/90 md:mx-0">
                  Fancy Digitals exists to make complex digital journeys feel manageable, thoughtful, and well-structured.
                </p>

                <div className="mt-8 flex flex-col items-center gap-3 sm:flex-row md:justify-start">
                  <Link
                    href="/contact"
                    className="group inline-flex w-full sm:w-auto items-center justify-center gap-2 rounded-xl bg-white px-8 py-4 font-bold text-[#075a01] shadow-lg transition-all hover:-translate-y-1 hover:shadow-xl"
                  >
                    Let&apos;s Work Together
                    <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" />
                  </Link>
                  <a
                    href="https://wa.me/2349034360785"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex w-full sm:w-auto items-center justify-center gap-2 rounded-xl border-2 border-white/30 px-8 py-4 font-bold text-white transition-all hover:bg-white/10"
                  >
                    <MessageCircle className="h-5 w-5" />
                    Chat on WhatsApp
                  </a>
                </div>
              </div>

              <div className="hidden md:block">
                <div className="relative">
                  <div className="relative h-48 w-48 overflow-hidden rounded-full border-4 border-white/20 shadow-2xl">
                    <Image
                      src={founder.image}
                      alt="Bashir Ismail"
                      fill
                      className="object-cover object-center"
                      sizes="192px"
                    />
                  </div>
                  <div className="absolute -bottom-2 left-1/2 -translate-x-1/2 rounded-full bg-white px-4 py-2 shadow-lg whitespace-nowrap">
                    <p className="text-sm font-bold text-gray-900">{founder.name}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ============ QUICK CONTACT ============ */}
      <section className="relative px-5 pb-16 md:px-10">
        <div className="mx-auto max-w-4xl text-center">
          <p className="text-gray-500">
            Want to learn more?{" "}
            <Link href="/contact" className="font-semibold text-[#075a01] hover:underline">Contact me</Link>{" "}
            or call{" "}
            <a href="tel:+2349045547761" className="font-semibold text-[#075a01] hover:underline">+234 904 554 7761</a>
          </p>
        </div>
      </section>
    </main>
  );
}