const BASE_URL = "https://fancydigitals.com.ng";

export const metadata = {
  title: "Privacy Policy | Fancy Digitals",
  description:
    "Privacy Policy for Fancy Digitals — how we collect, use and protect your data when you use our website and free online tools.",
  alternates: {
    canonical: `${BASE_URL}/privacy-policy`,
  },
};

export default function PrivacyPolicyPage() {
  return (
    <main className="bg-white pt-28 pb-32">
      <div className="mx-auto max-w-3xl px-6">

        <h1 className="text-4xl font-bold text-gray-900 mb-4">Privacy Policy</h1>
        <p className="text-sm text-gray-400 mb-12">Last updated: June 2025</p>

        <div className="prose prose-gray max-w-none space-y-10 text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">1. Introduction</h2>
            <p>
              Welcome to Fancy Digitals ("we", "our", "us"). We are a web design, SEO, branding and
              digital tools agency based in Lagos, Nigeria. Our website is located at{" "}
              <a href={BASE_URL} className="text-[#075a01] hover:underline">{BASE_URL}</a>.
            </p>
            <p className="mt-3">
              This Privacy Policy explains how we collect, use, disclose and protect information
              when you visit our website or use our free online tools. By using our website, you
              agree to the terms of this policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">2. Information We Collect</h2>
            <h3 className="font-semibold text-gray-800 mb-2">2.1 Information you provide directly</h3>
            <ul className="list-disc pl-6 space-y-1">
              <li>Contact form submissions — name, email address, and message</li>
              <li>Waitlist sign-ups — email address and tool name</li>
              <li>Service enquiries — name, email, and project details</li>
            </ul>

            <h3 className="font-semibold text-gray-800 mt-4 mb-2">2.2 Information collected automatically</h3>
            <ul className="list-disc pl-6 space-y-1">
              <li>Pages visited and time spent on each page</li>
              <li>Browser type, device type, and operating system</li>
              <li>IP address and approximate geographic location</li>
              <li>Referring website or search query</li>
              <li>Tool usage events — which tools you open and use</li>
            </ul>

            <h3 className="font-semibold text-gray-800 mt-4 mb-2">2.3 What our tools do NOT collect</h3>
            <p>
              All Fancy Digitals free tools run entirely in your browser. The text you type into
              the Word Counter, the passwords generated by the Password Generator, the invoices
              you create, the QR codes you generate, and all other tool inputs and outputs are
              never sent to our servers. They never leave your device.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">3. How We Use Your Information</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>To respond to contact form enquiries and service requests</li>
              <li>To send waitlist notifications when a tool launches</li>
              <li>To analyse website traffic and improve our content and tools</li>
              <li>To understand which tools are most used and where users come from</li>
              <li>To comply with legal obligations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">4. Cookies</h2>
            <p>
              We use cookies and similar tracking technologies to operate and improve our website.
              Cookies are small text files stored on your device by your browser.
            </p>
            <h3 className="font-semibold text-gray-800 mt-4 mb-2">Types of cookies we use:</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Essential cookies:</strong> Required for the website to function. These
                cannot be disabled.
              </li>
              <li>
                <strong>Analytics cookies:</strong> We use Google Analytics 4 to understand how
                visitors use our website. Google Analytics collects information such as pages
                visited, time on site, and general location. This data is anonymous and aggregated.
              </li>
              <li>
                <strong>Advertising cookies:</strong> We use Google AdSense to display
                advertisements on our website. Google may use cookies to serve ads based on your
                prior visits to our website or other websites. You can opt out of personalised
                advertising by visiting{" "}
                <a
                  href="https://www.google.com/settings/ads"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#075a01] hover:underline"
                >
                  Google Ads Settings
                </a>.
              </li>
            </ul>
            <p className="mt-3">
              You can control cookies through your browser settings. Disabling cookies may affect
              the functionality of some features of our website.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">5. Google AdSense and Advertising</h2>
            <p>
              Fancy Digitals uses Google AdSense to display advertisements. Google AdSense uses
              cookies to serve ads based on a user's prior visits to our website and other sites
              on the internet.
            </p>
            <p className="mt-3">
              Third-party vendors, including Google, use cookies to serve ads based on prior
              visits to our website. Google's use of advertising cookies enables it and its
              partners to serve ads to our visitors based on their visit to our site and other
              sites on the internet.
            </p>
            <p className="mt-3">
              Users may opt out of personalised advertising by visiting{" "}
              <a
                href="https://www.aboutads.info"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#075a01] hover:underline"
              >
                www.aboutads.info
              </a>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">6. Google Analytics</h2>
            <p>
              We use Google Analytics 4 to analyse website traffic. Google Analytics collects
              data such as pages visited, session duration, device type, and approximate location.
              All data is anonymised and aggregated. We do not share individual user data with
              any third party.
            </p>
            <p className="mt-3">
              You can opt out of Google Analytics tracking by installing the{" "}
              <a
                href="https://tools.google.com/dlpage/gaoptout"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#075a01] hover:underline"
              >
                Google Analytics Opt-out Browser Add-on
              </a>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">7. Data Sharing</h2>
            <p>
              We do not sell, trade, or rent your personal information to third parties. We may
              share anonymised, aggregated data with analytics providers to improve our services.
              We may disclose personal information if required by law or to protect our rights.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">8. Data Retention</h2>
            <p>
              Contact form and waitlist data is retained for as long as necessary to respond to
              your enquiry or fulfil your request. Analytics data is retained according to Google
              Analytics default retention settings (26 months).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">9. Your Rights</h2>
            <p>You have the right to:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Request access to personal data we hold about you</li>
              <li>Request correction of inaccurate personal data</li>
              <li>Request deletion of your personal data</li>
              <li>Opt out of marketing communications at any time</li>
              <li>Withdraw consent where processing is based on consent</li>
            </ul>
            <p className="mt-3">
              To exercise any of these rights, contact us at{" "}
              <a href="mailto:hello@fancydigitals.com.ng" className="text-[#075a01] hover:underline">
                hello@fancydigitals.com.ng
              </a>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">10. Children's Privacy</h2>
            <p>
              Our website and tools are not directed at children under the age of 13. We do not
              knowingly collect personal information from children. If you believe a child has
              provided us with personal information, please contact us and we will delete it
              immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">11. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of any
              significant changes by updating the date at the top of this page. Continued use of
              our website after changes constitutes acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">12. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy or how we handle your data,
              please contact us:
            </p>
            <div className="mt-3 space-y-1">
              <p><strong>Fancy Digitals</strong></p>
              <p>Lagos, Nigeria</p>
              <p>
                Email:{" "}
                <a href="mailto:hello@fancydigitals.com.ng" className="text-[#075a01] hover:underline">
                  hello@fancydigitals.com.ng
                </a>
              </p>
              <p>
                Phone:{" "}
                <a href="tel:+2349045547761" className="text-[#075a01] hover:underline">
                  +234 904 554 7761
                </a>
              </p>
              <p>
                Website:{" "}
                <a href={BASE_URL} className="text-[#075a01] hover:underline">
                  {BASE_URL}
                </a>
              </p>
            </div>
          </section>

        </div>
      </div>
    </main>
  );
}