const BASE_URL = "https://fancydigitals.com.ng";

export const metadata = {
  title: "Terms of Service | Fancy Digitals",
  description:
    "Terms of Service for Fancy Digitals — the rules and conditions governing use of our website, free tools and digital services.",
  alternates: {
    canonical: `${BASE_URL}/terms`,
  },
};

export default function TermsPage() {
  return (
    <main className="bg-white pt-28 pb-32">
      <div className="mx-auto max-w-3xl px-6">

        <h1 className="text-4xl font-bold text-gray-900 mb-4">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-12">Last updated: June 2025</p>

        <div className="prose prose-gray max-w-none space-y-10 text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">1. Agreement to Terms</h2>
            <p>
              By accessing or using the Fancy Digitals website at{" "}
              <a href={BASE_URL} className="text-[#075a01] hover:underline">{BASE_URL}</a> and
              our free online tools, you agree to be bound by these Terms of Service. If you
              do not agree to these terms, please do not use our website or tools.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">2. Free Tools</h2>
            <p>
              Fancy Digitals provides a suite of free online tools including but not limited to:
              Word Counter, Password Generator, Invoice Generator, QR Code Generator, Color
              Palette Generator, Hashtag Generator, Unit Converter, and SEO Meta Tag Generator.
            </p>
            <p className="mt-3">These tools are provided free of charge with no sign-up required. By using our tools you acknowledge that:</p>
            <ul className="list-disc pl-6 space-y-2 mt-3">
              <li>All tool processing happens in your browser. No data you enter is sent to our servers.</li>
              <li>Tools are provided as-is without warranty of any kind.</li>
              <li>We do not guarantee uninterrupted availability of any tool.</li>
              <li>You use the tools at your own risk.</li>
              <li>Generated outputs — including passwords, invoices, QR codes, and color palettes — are your sole responsibility to verify before use.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">3. Intellectual Property</h2>
            <p>
              All content on the Fancy Digitals website — including text, graphics, logos, tool
              designs, and code — is the intellectual property of Fancy Digitals and protected
              by applicable copyright laws. You may not reproduce, distribute, or create
              derivative works without our express written permission.
            </p>
            <p className="mt-3">
              Outputs generated by our tools — such as QR codes, invoices, color palettes, and
              hashtag sets — are yours to use freely including for commercial purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">4. Acceptable Use</h2>
            <p>You agree not to use our website or tools to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-3">
              <li>Violate any applicable law or regulation</li>
              <li>Generate fraudulent invoices or documents intended to deceive</li>
              <li>Create QR codes that link to malicious, illegal, or harmful content</li>
              <li>Attempt to reverse engineer, copy, or resell our tools</li>
              <li>Overload our servers through automated scraping or excessive requests</li>
              <li>Use our tools to facilitate spam, phishing, or any form of fraud</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">5. Digital Services</h2>
            <p>
              Fancy Digitals provides paid digital services including web design, SEO, branding,
              email marketing, AI automation, and social media management. Separate agreements
              govern each client engagement. These Terms of Service apply to use of our website
              and free tools only.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">6. Disclaimer of Warranties</h2>
            <p>
              Our website and tools are provided on an "as is" and "as available" basis without
              any warranties of any kind, either express or implied. We do not warrant that:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-3">
              <li>The website will be uninterrupted or error-free</li>
              <li>Results obtained from using our tools will be accurate or reliable</li>
              <li>Any errors in the tools will be corrected</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">7. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Fancy Digitals shall not be liable for
              any indirect, incidental, special, consequential, or punitive damages arising from
              your use of our website or tools. This includes but is not limited to loss of
              revenue, data, or business opportunities.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">8. Third-Party Links and Advertising</h2>
            <p>
              Our website may display advertisements served by Google AdSense and may contain
              links to third-party websites. We are not responsible for the content, privacy
              practices, or terms of any third-party website. Clicking on advertisements or
              third-party links is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">9. Governing Law</h2>
            <p>
              These Terms of Service are governed by the laws of the Federal Republic of Nigeria.
              Any disputes arising from these terms shall be subject to the exclusive jurisdiction
              of the courts of Lagos State, Nigeria.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">10. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms of Service at any time. We will update
              the date at the top of this page when changes are made. Continued use of our
              website after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">11. Contact</h2>
            <p>For questions about these Terms of Service, contact us:</p>
            <div className="mt-3 space-y-1">
              <p><strong>Fancy Digitals</strong></p>
              <p>Lagos, Nigeria</p>
              <p>
                Email:{" "}
                <a href="mailto:hello@fancydigitals.com.ng" className="text-[#075a01] hover:underline">
                  hello@fancydigitals.com.ng
                </a>
              </p>
              <p>
                Phone:{" "}
                <a href="tel:+2349045547761" className="text-[#075a01] hover:underline">
                  +234 904 554 7761
                </a>
              </p>
            </div>
          </section>

        </div>
      </div>
    </main>
  );
}